const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),elements=new Map(),storage=new Map(),context={window:{},console};vm.createContext(context);
for(const f of ['world-data.js','engine.js','rts-navigation.js','rts-engine.js','session-gate.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets/js',f),'utf8'),context);
Object.assign(context,{$:id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)}});
vm.runInContext("const SAVE_KEY='guest',RT=BaraRTS,gate=new AccountGate(),groups=new Map();let activeSaveKey=null,game=new RT.Game(),speed=1,screen='welcome',saveTimer=0,dirty=false,pendingBuild=null;const simulationClock={reset(){}};function handleEvent(){}function advanceGame(){}function openGamePanel(){}function focusVillage(){}function renderUI(){}function refreshGate(){}function clearSelection(){}function start(){return gate.canPlay;}",context);
context.save=()=>{if(vm.runInContext('gate.canPlay',context))storage.set(vm.runInContext('activeSaveKey',context),vm.runInContext('game.serialize()',context));};
const source=fs.readFileSync(path.join(root,'assets/js/rts-game.js'),'utf8');vm.runInContext(source.slice(source.indexOf('// Narrow interface')),context);
const adapter=context.window.BentengBara,tests=[];function test(name,fn){fn();tests.push(name);}
test('Anonymous visitors cannot enter or attach a player campaign',()=>{assert(!adapter.canPlay());assert(!adapter.enter());assert.throws(()=>adapter.attach('6xg-account:did:privy:a',null));assert.equal(storage.size,0);});
test('A verified identity can only attach its own campaign and new resources are zero',()=>{adapter.setIdentity('did:privy:a');assert.throws(()=>adapter.attach('6xg-account:did:privy:b',null));adapter.attach('6xg-account:did:privy:a',null);assert(adapter.canPlay());assert.equal(JSON.parse(adapter.snapshot()).state.resources.wood,0);});
test('Switching identities preserves independent account snapshots and locks during loading',()=>{vm.runInContext('game.s.time=200',context);const first=adapter.snapshot();adapter.setIdentity('did:privy:b');assert(!adapter.canPlay());assert.equal(storage.get('6xg-account:did:privy:a'),first);adapter.attach('6xg-account:did:privy:b',null);vm.runInContext('game.s.time=300',context);const second=adapter.snapshot();adapter.setIdentity('did:privy:a');adapter.attach('6xg-account:did:privy:a',first);assert.equal(storage.get('6xg-account:did:privy:b'),second);assert.equal(JSON.parse(adapter.snapshot()).state.time,200);});
test('Invalid cloud snapshots do not replace a valid account campaign',()=>{const before=adapter.snapshot();assert.throws(()=>adapter.attach('6xg-account:did:privy:a','{"version":3,"state":{}}'),/tidak valid/);assert.equal(adapter.snapshot(),before);});
test('Signing out returns to the login gate without exposing or overwriting old guest progress',()=>{const legacy=vm.runInContext('new Kingdom().serialize()',context);storage.set('guest',legacy);adapter.detach();assert(!adapter.canPlay());assert(!adapter.enter());assert.equal(storage.get('guest'),legacy);assert.equal(adapter.legacySnapshot(),legacy);assert.equal(JSON.parse(adapter.snapshot()).state.resources.gold,0);});
test('Migrating an existing account backs up the version-2 snapshot before saving RTS format',()=>{const legacy=storage.get('guest');adapter.setIdentity('did:privy:legacy');adapter.attach('6xg-account:did:privy:legacy',legacy);assert.equal(storage.get('6xg-account:did:privy:legacy:before-rts'),legacy);assert.equal(JSON.parse(storage.get('6xg-account:did:privy:legacy')).version,3);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
