import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import '../assets/js/account-photo.js';
import '../assets/js/farm-engine.js';
const P=globalThis.BaraAccountPhoto;
const small='https://pbs.twimg.com/profile_images/123/photo_normal.jpg',photo='https://pbs.twimg.com/profile_images/123/photo.jpg';
assert.equal(P.twitterURL(small),photo);
for(const invalid of ['http://pbs.twimg.com/profile_images/1/a.jpg','https://evil.example/a.jpg','https://pbs.twimg.com.evil.example/profile_images/1/a.jpg','https://pbs.twimg.com@evil.example/profile_images/1/a.jpg','https://pbs.twimg.com:8080/profile_images/1/a.jpg','data:image/svg+xml;base64,AAA','javascript:alert(1)','https://pbs.twimg.com/media/a.jpg','https://pbs.twimg.com/profile_images/1/a.jpg?token=secret',null,42])assert.equal(P.twitterURL(invalid),null);
const farm=new BaraFarm.Farm({clock:()=>1791100000000}),before=farm.serialize();
assert.equal(P.source(farm.s.profile,small),photo);
const uploaded=JSON.parse(await readFile(new URL('./profile-photo.json',import.meta.url),'utf8')).photo;
assert(farm.updateProfile({...farm.s.profile,photo:uploaded}).ok);assert.equal(P.source(farm.s.profile,small),uploaded);
assert(farm.updateProfile({name:'Pekebun',farmName:'Kebunku',avatar:'bee',useAccountPhoto:false}).ok);
const restored=new BaraFarm.Farm({save:farm.serialize(),clock:()=>1791100000000});assert.equal(P.source(restored.s.profile,small),null);assert.equal(restored.s.profile.avatar,'bee');
assert(restored.updateProfile({...restored.s.profile,useAccountPhoto:true}).ok);assert.equal(P.source(restored.s.profile,small),photo);
assert(!restored.updateProfile({...restored.s.profile,useAccountPhoto:'false'}).ok);
assert.equal(JSON.parse(before).state.coins,restored.s.coins);assert.equal(restored.s.seeds.carrot,6);
const holder={textContent:'',ownerDocument:{createElement:()=>({})},replaceChildren(){this.child=null;this.textContent='';},append(img){this.child=img;img.parentElement=this;}};
P.render(holder,photo,'bee');assert.equal(holder.child.src,photo);assert.equal(holder.child.referrerPolicy,'no-referrer');holder.child.onerror();assert.equal(holder.textContent,'🐝');P.render(holder,photo,'bee');assert.equal(holder.child,null);assert.equal(holder.textContent,'🐝');
console.log('Account photos: secure URLs, upload priority, persistent avatar choice, unchanged farm, broken-image fallback passed.');
