const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {source}=require('./load-game.cjs')();
const context={Math,JSON,Date};vm.createContext(context);
vm.runInContext(source.split('// Browser interface.')[0]+';globalThis.Game=Kingdom;globalThis.Clock=SimulationClock;',context);
const tests=[];function test(name,fn){fn();tests.push(name);}function close(actual,expected){assert(Math.abs(actual-expected)<1e-6,`${actual} != ${expected}`);}
function fixture(){let now=1000,speed=1;let game=new context.Game();const clock=new context.Clock(()=>game,()=>speed,()=>now);game.start();return {get game(){return game;},clock,elapse(seconds){now+=seconds*1000;return clock.advance();},setSpeed(value){clock.advance();speed=value;},replace(){game=new context.Game();clock.reset();},pause(){clock.advance();game.pause();},resume(){clock.reset();game.start();},skip(seconds){now+=seconds*1000;}};}
test('A throttled background timer preserves all 30 seconds of production and construction',()=>{const f=fixture();assert(f.game.build('barracks'));f.elapse(30);close(f.game.s.time,30);close(f.game.s.resources.wood,55+2.25*30);assert.equal(f.game.s.levels.barracks,1);close(f.game.s.raidTimer,120);assert(f.game.running);});
test('Animation and interval callbacks cannot double count the same elapsed time',()=>{const f=fixture();f.elapse(1);const state=f.game.serialize();f.clock.advance();assert.equal(f.game.serialize(),state);for(let i=0;i<100;i++){f.elapse(.01);f.clock.advance();}close(f.game.s.time,2);});
test('Manual pause excludes a long hidden interval even without timer callbacks',()=>{const f=fixture();f.elapse(3);f.game.build('barracks');f.pause();const state=f.game.serialize();f.skip(600);f.resume();assert.equal(f.game.serialize(),state);f.elapse(2);close(f.game.s.time,5);close(f.game.s.construction.left,8);});
test('Speed changes take effect after previously elapsed time is settled',()=>{const f=fixture();f.skip(5);f.setSpeed(2);f.elapse(4);close(f.game.s.time,13);f.skip(3);f.setSpeed(1);f.elapse(2);close(f.game.s.time,21);});
test('Recruitment, expedition outcomes, and raids resolve during delayed callbacks',()=>{const f=fixture();f.game.s.levels.barracks=1;f.game.s.army.soldier=6;assert(f.game.train('soldier'));assert(f.game.attack(0));f.elapse(35);assert.equal(f.game.s.training.length,0);assert(f.game.s.captured[0]);assert.equal(f.game.s.expedition,null);assert.equal(f.game.s.army.soldier,6);f.game.s.raidTimer=2;f.elapse(11);assert.equal(f.game.s.wave,1);assert.equal(f.game.s.raid,null);assert(f.game.s.log.some(e=>e.text.includes('Gelombang 1')));});
test('A long suspended session stops at defeat instead of advancing a finished campaign',()=>{const f=fixture();f.elapse(86400);assert.equal(f.game.s.result,'lost');assert(!f.game.running);assert(f.game.s.time<86400);const state=f.game.serialize();f.elapse(120);assert.equal(f.game.serialize(),state);});
test('Fresh campaigns and restored saves do not inherit previous elapsed time',()=>{const f=fixture();f.elapse(10);const saved=f.game.serialize();f.skip(500);f.replace();assert(f.game.load(saved));f.resume();f.elapse(2);close(f.game.s.time,12);f.replace();f.resume();f.elapse(1);close(f.game.s.time,1);});
test('Clock moving backwards cannot subtract progress or run negative production',()=>{const f=fixture();f.elapse(3);const state=f.game.serialize();f.elapse(-2);assert.equal(f.game.serialize(),state);f.elapse(1);close(f.game.s.time,4);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
