const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={Math,WORLD_DATA:{bounds:{width:3200,height:2200,originX:1100,originY:740}}};vm.createContext(context);vm.runInContext(fs.readFileSync('assets/js/camera.js','utf8')+'\n'+fs.readFileSync('assets/js/farm-camera.js','utf8')+'\nglobalThis.Camera=FarmCamera;globalThis.Gesture=MapGesture;',context);
const close=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`),tests=[];const test=(name,fn)=>{fn();tests.push(name);};function fresh(){const c=new context.Camera();c.resize(1280,720);return c;}
test('The default and home camera face north and clearly expose building fronts',()=>{const c=fresh();close(c.yaw,0);close(c.tilt,40*Math.PI/180);const ground=c.worldToScreen(1592,1084),roof=c.worldToScreen(1592,1084,120),east=c.worldToScreen(1692,1084),north=c.worldToScreen(1592,984);close(ground.x,roof.x);assert(roof.y<ground.y-90,'Building height must occupy over 90 pixels, revealing front walls rather than mostly roofs');close(east.y,ground.y);close(north.x,ground.x);assert(east.x>ground.x&&north.y<ground.y);c.rotate(.9);c.tilt=Math.PI/2;c.home();close(c.yaw,0);close(c.tilt,40*Math.PI/180);});
test('Ground picking agrees with projected plots at every camera rotation',()=>{const c=fresh();for(let i=0;i<16;i++){c.rotate(Math.PI/8);for(const[x,y]of[[1524,1010],[1592,1084],[1660,1158],[2050,1350]]){const p=c.worldToScreen(x,y),q=c.screenToWorld(p.x,p.y);close(q.x,x);close(q.y,y);}}});
test('Dragging follows screen motion after the camera rotates',()=>{const c=fresh();c.rotate(.7);const before=c.worldToScreen(1590,1135);c.pan(80,-60);const after=c.worldToScreen(1590,1135);close(after.x-before.x,80);close(after.y-before.y,-60);});
test('Zoom keeps the clicked ground point stationary at a rotated angle',()=>{const c=fresh();c.rotate(.6);const before=c.screenToWorld(530,280);c.zoomAt(1.3,530,280);const after=c.screenToWorld(530,280);close(before.x,after.x);close(before.y,after.y);});
test('Clamped camera corners remain within the large map on phones and desktops',()=>{const c=fresh();for(const[w,h]of[[320,600],[1280,720],[1920,1080]]){c.resize(w,h);for(let i=0;i<16;i++){c.rotate(Math.PI/8);c.zoomAt(.001);for(const[x,y]of[[0,0],[3200,2200],[1e6,-1e6]]){c.focus(x,y);for(const p of c.corners)assert(p.x>=-1e-6&&p.y>=-1e-6&&p.x<=3200+1e-6&&p.y<=2200+1e-6);}}}});
test('A plot click still selects its saved position after zoom, pan, and rotation',()=>{const c=fresh();c.rotate(.9);c.pan(50,40);c.zoomAt(1.3);let selected;const g=new context.Gesture(c,p=>selected=p),p=c.worldToScreen(1592,1084);g.down(1,p.x,p.y);g.up(1,p.x,p.y);close(selected.x,1592);close(selected.y,1084);});
test('A pinch cannot plant a crop when either finger is lifted',()=>{const c=fresh();c.rotate(.5);let planted=0;const g=new context.Gesture(c,()=>planted++);g.down(1,450,320);g.down(2,550,320);g.move(2,620,320);g.up(2,620,320);g.up(1,450,320);assert.equal(planted,0);assert.equal(g.pointers.size,0);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
