const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/farm-engine.js','utf8'),c);const F=c.BaraFarm;let now=1791200000000,count=0;
const plain=v=>JSON.parse(JSON.stringify(v));
function test(name,fn){fn();count++;console.log('✓ '+name);}
function fresh(level=15){const f=new F.Farm({clock:()=>now});f.s.progress.xp=F.LEVEL_XP[level-1];f.s.coins=5000;f.s.materials={wood:200,stone:200,meat:200};return f;}
function pier(){const f=fresh(),p=F.pierPoint(1460);assert(f.build('pier',{x:p.x,y:p.y},0).ok);now+=90000;f.now();assert(f.fishingStarter().ok);return f;}
function cast(f,seed=420){assert(f.startFishing(0,'worm',seed).ok);return f.s.fishing.cast;}
function catchFish(f){const c=f.s.fishing.cast;now=c.biteAt;assert(f.hookFish(c.id).ok);for(let i=1;i<=3;i++){now=c.hookedAt+i*3000;const r=f.reelFish(c.id);assert(r.ok);if(i===3)return r;}}
test('v9 saves retain farm progress and start with empty fishing inventory, without repeating seed gifts',()=>{const f=fresh();f.plant(0,'carrot');const old=plain(JSON.parse(f.serialize()));old.version=9;delete old.state.fishing;const g=new F.Farm({save:old,clock:()=>now});assert.equal(g.s.seeds.carrot,5);assert.equal(g.s.coins,f.s.coins);assert.equal(g.s.plots[0].readyAt,f.s.plots[0].readyAt);assert.equal(g.s.fishing.bait.worm,0);assert(!g.s.fishing.starter);assert.equal(JSON.parse(g.serialize()).version,10);F.validateSave(JSON.parse(g.serialize()));});
test('starter bait is gated by level, claimed once, and persists across reloads',()=>{const f=fresh(2);assert(!f.fishingStarter().ok);f.s.progress.xp=80;assert(f.fishingStarter().ok);assert.equal(f.s.fishing.bait.worm,3);assert(!f.fishingStarter().ok);const g=new F.Farm({save:f.serialize(),clock:()=>now});assert(!g.fishingStarter().ok);assert.equal(g.s.fishing.bait.worm,3);});
test('pier reaches either riverbank, rejects open water and the bridge, and moves without spending again',()=>{for(const rotation of[0,2])for(const y of[100,700,1460,2050]){const f=fresh(),p=F.pierPoint(y,rotation);assert(f.build('pier',{x:p.x,y:p.y},rotation).ok);F.validateSave(JSON.parse(f.serialize()));}const f=pier(),before=f.s.materials.wood;assert(!f.moveBuilding(0,{x:1700,y:1500},0).ok);assert(!f.checkPlacement('pier',{x:F.pierPoint(1115).x,y:1115},0).ok);assert(!f.checkPlacement('pier',{x:640,y:1460},1).ok);const p=F.pierPoint(700,2);assert(f.moveBuilding(0,{x:p.x,y:p.y},2).ok);assert.equal(f.s.materials.wood,before);F.validateSave(JSON.parse(f.serialize()));});
test('casting consumes one bait, uses a completed pier, and early hook or duplicate cast cannot cheat time',()=>{const f=pier(),c=cast(f);assert.equal(f.s.fishing.bait.worm,2);assert(!f.hookFish(c.id).ok);assert(!f.startFishing(0,'worm',333).ok);assert.equal(f.s.fishing.bait.worm,2);assert(!f.moveBuilding(0,{x:F.pierPoint(700).x,y:700},0).ok);assert(!f.sellBuilding(0).ok);assert(!f.startFishing(0,'unknown',333).ok);F.validateSave(JSON.parse(f.serialize()));});
test('server rhythm rejects rapid reels and produces exactly one fish, XP and record after three valid windows',()=>{const f=pier(),c=cast(f);now=c.biteAt;assert(f.hookFish(c.id).ok);assert(!f.reelFish(c.id).ok);const beforeXP=f.s.progress.xp;for(let i=1;i<=3;i++){now=c.hookedAt+i*3000;const r=f.reelFish(c.id);assert(r.ok);if(i<3)assert(!f.reelFish(c.id).ok);else{assert(r.caught);assert.equal(f.s.fishing.fish[r.caught.kind],1);assert.equal(f.s.progress.xp,beforeXP+F.FISH[r.caught.kind].xp);}}assert.equal(f.s.fishing.caught,1);assert.equal(f.used,1);assert.equal(f.s.fishing.records.length,1);assert(!f.reelFish(c.id).ok);F.validateSave(JSON.parse(f.serialize()));});
test('late hook, late reel, cancel and reload never refund consumed bait or grant a catch',()=>{const f=pier(),c=cast(f);now=c.expiresAt+1;assert(f.hookFish(c.id).escaped);assert.equal(f.s.fishing.bait.worm,2);assert.equal(f.used,0);const d=cast(f,87);now=d.biteAt;f.hookFish(d.id);const g=new F.Farm({save:f.serialize(),clock:()=>now});now=d.hookedAt+4601;assert(g.reelFish(d.id).escaped);assert.equal(g.s.fishing.caught,0);assert.equal(g.s.fishing.bait.worm,1);const e=cast(g);assert(g.cancelFishing(e.id).ok);assert.equal(g.s.fishing.bait.worm,0);assert(!g.cancelFishing(e.id).ok);});
test('a fish remains on the line if other work fills the bag, then can be kept once space is free',()=>{const f=pier();f.s.produce.carrot=19;cast(f);f.s.produce.carrot=20;const r=catchFish(f);assert(r.full&&r.landed);assert.equal(f.s.fishing.cast.reels,3);assert.equal(f.s.fishing.caught,0);F.validateSave(JSON.parse(f.serialize()));now+=86400000;f.sell('carrot',1);const kept=f.reelFish(f.s.fishing.cast.id);assert(kept.caught);assert.equal(f.used,20);assert.equal(f.s.fishing.caught,1);assert(!f.startFishing(0,'worm',8).ok);F.validateSave(JSON.parse(f.serialize()));});
test('fish sales use real inventory, count toward bag capacity and protect coin/material limits',()=>{const f=pier();cast(f);const r=catchFish(f),key=r.caught.kind,before=f.s.coins;assert(f.sellFish(key,1).ok);assert.equal(f.s.coins,before+F.FISH[key].sell);assert.equal(f.used,0);assert(!f.sellFish(key,1).ok);assert(!f.sellFish(key,-1).ok);assert(!f.buyBait('worm',101).ok);f.s.fishing.bait.worm=1000;assert(!f.buyBait('worm',1).ok);});
test('rod upgrades have meaningful level/cost gates and cannot change an active cast',()=>{const f=pier();f.s.progress.xp=80;assert(!f.upgradeRod().ok);f.s.progress.xp=260;assert(f.upgradeRod().ok);assert.equal(f.s.fishing.rod,2);cast(f);assert(!f.upgradeRod().ok);f.cancelFishing(f.s.fishing.cast.id);f.s.progress.xp=650;assert(f.upgradeRod().ok);assert(!f.upgradeRod().ok);F.validateSave(JSON.parse(f.serialize()));});
test('save validation rejects forged bait, clocks, fish, pier orientation, records and reel progress',()=>{const f=pier();cast(f);for(const change of[s=>s.fishing.bait.worm=-1,s=>s.fishing.fish.tilapia=1,s=>s.fishing.cast.biteAt--,s=>s.fishing.cast.seed=-1,s=>s.fishing.cast.conditions.night=!s.fishing.cast.conditions.night,s=>s.fishing.cast.reels=3,s=>s.fishing.cast.rod=3,s=>s.buildings[0].rotation=1,s=>s.fishing.records=[{kind:'tilapia',length:900,at:now}]]){const bad=JSON.parse(f.serialize());change(bad.state);assert.throws(()=>F.validateSave(bad));}});
test('fishing rain uses the same world weather and night follows Jakarta, without storing location',()=>{const w={};vm.createContext(w);vm.runInContext(fs.readFileSync('assets/js/farm-weather.js','utf8'),w);for(let i=0;i<100;i++){const at=1791100000000+i*59003;assert.equal(F.fishingConditions(at).rain,w.FarmWeather.at(at).rain>.15);}assert(F.fishingConditions(Date.parse('2026-10-05T13:00:00Z')).night);assert(!F.fishingConditions(Date.parse('2026-10-05T03:00:00Z')).night);for(const bait of Object.keys(F.BAITS))for(let rod=1;rod<=3;rod++){const o=F.fishingOutcome(888,bait,rod,{night:true,rain:true});assert(F.FISH[o.kind]);assert(o.length>=F.FISH[o.kind].min&&o.length<=F.FISH[o.kind].max);}});
test('pier upgrades mature at exact deadlines, preserve saves and location, and stop at level 5',()=>{const f=pier();f.s.materials={wood:1000,stone:1000,meat:1000};const point=plain(F.pierPoint(1460)),before=f.s.coins;for(let target=2;target<=5;target++){const q=f.upgradeQuote(0);assert(q.ok);assert.equal(q.required,(target-1)*3);const stock=plain(f.s.materials);assert(f.upgradeBuilding(0).ok);assert.equal(f.s.coins,before-[100,250,450,700][target-2]);assert.equal(f.s.materials.wood,stock.wood-q.cost.wood);assert.equal(f.s.materials.stone,stock.stone-q.cost.stone);assert(!f.upgradeBuilding(0).ok);const loaded=new F.Farm({save:f.serialize(),clock:()=>now});assert.equal(loaded.buildingLevel(loaded.s.buildings[0]),target-1);now=f.s.buildings[0].upgrade.readyAt-1;f.now();assert.equal(f.s.buildings[0].level,target-1);now++;f.now();assert.equal(f.s.buildings[0].level,target);assert.equal(f.s.buildings[0].upgrade,null);assert.equal(f.s.buildings[0].x,point.x);assert.equal(f.s.buildings[0].y,point.y);F.validateSave(JSON.parse(f.serialize()));}assert(!f.upgradeBuilding(0).ok);const g=new F.Farm({save:f.serialize(),clock:()=>now});assert.equal(g.s.buildings[0].level,5);assert(g.moveBuilding(0,F.pierPoint(700,2),2).ok);assert.equal(g.s.buildings[0].level,5);});
test('upgrading and live or landed fishing cannot change each other or spend bait accidentally',()=>{const f=pier(),c=cast(f),coins=f.s.coins,stock=f.s.materials.wood;assert(!f.upgradeBuilding(0).ok);assert.equal(f.s.coins,coins);assert.equal(f.s.materials.wood,stock);f.s.produce.carrot=20;assert(catchFish(f).full);assert(!f.upgradeBuilding(0).ok);f.sell('carrot',1);assert(f.reelFish(c.id).caught);assert(f.upgradeBuilding(0).ok);const bait=f.s.fishing.bait.worm;assert(!f.startFishing(0,'worm',555).ok);assert.equal(f.s.fishing.bait.worm,bait);now=f.s.buildings[0].upgrade.readyAt;f.now();f.sell('carrot',1);assert(f.startFishing(0,'worm',555).ok);const castAt2=plain(f.s.fishing.cast),xp=f.s.progress.xp,result=catchFish(f);assert.deepEqual(plain(result.caught),plain(F.fishingOutcome(castAt2.seed,castAt2.bait,castAt2.rod,castAt2.conditions,2)));assert.equal(result.xp,F.FISH[result.caught.kind].xp+2);assert.equal(f.s.progress.xp,xp+result.xp);F.validateSave(JSON.parse(f.serialize()));});
test('legacy upgraded piers retain their original rare-fish odds',()=>{for(const bait of Object.keys(F.BAITS))for(const conditions of[{night:false,rain:false},{night:true,rain:true}]){let previous=0;for(let level=1;level<=5;level++){let rare=0;for(let seed=0;seed<10000;seed++){const r=F.fishingOutcome(seed,bait,1,conditions,level,2);if(r.kind==='snakehead')rare++;assert(r.length>=F.FISH[r.kind].min&&r.length<=F.FISH[r.kind].max);if(level===1)assert.deepEqual(plain(r),plain(F.fishingOutcome(seed,bait,1,conditions,1,2)));}assert(rare>previous);previous=rare;assert.equal(F.pierFishingBonus(level).xp,(level-1)*2);}}});
test('expired casts allow pier upgrades and their old saves remain valid after work completes',()=>{const f=pier(),c=cast(f);now=c.expiresAt+1;assert(f.upgradeBuilding(0).ok);now=f.s.buildings[0].upgrade.readyAt;f.now();F.validateSave(JSON.parse(f.serialize()));assert(f.reelFish(c.id).escaped);assert.equal(f.s.fishing.caught,0);assert.equal(f.s.fishing.bait.worm,2);});
test('nine species have bounded catches and Arapaima keeps a 0.1% chance independent of gear and weather',()=>{
 assert.equal(Object.keys(F.FISH).length,9);assert.equal(F.FISH.arapaima.chance,.001);const observed=new Set();let legendary=0;
 for(let seed=0;seed<1000000;seed++){const r=F.fishingOutcome(seed,'worm',1,{night:false,rain:false});observed.add(r.kind);if(r.kind==='arapaima')legendary++;assert(r.length>=F.FISH[r.kind].min&&r.length<=F.FISH[r.kind].max);}
 assert.equal(observed.size,9);assert(legendary>=950&&legendary<=1050,'million-cast rate must be close to 0.1%');
 const seedList=Array.from({length:20000},(_,i)=>(Math.imul(i,2654435761)>>>0)),base=seedList.filter(seed=>F.fishingOutcome(seed,'worm',1,{night:false,rain:false}).kind==='arapaima');assert(base.length>0);
 for(const bait of Object.keys(F.BAITS))for(let rod=1;rod<=3;rod++)for(let pier=1;pier<=5;pier++)for(const night of[false,true])for(const rain of[false,true])assert.deepEqual(seedList.filter(seed=>F.fishingOutcome(seed,bait,rod,{night,rain},pier).kind==='arapaima'),base);
 console.log('Observed Arapaima: '+legendary+' / 1,000,000 casts');
});
test('legacy four-species inventory and unfinished casts keep their items, clocks and exact original outcome',()=>{
 const f=pier();f.s.fishing.fish.carp=2;f.s.fishing.caught=2;f.s.fishing.best=40;f.s.fishing.records=[{kind:'carp',length:40,at:now}];const c=cast(f,75319),old=JSON.parse(f.serialize());delete old.state.fishing.cast.poolVersion;for(const key of['gourami','pacu','pangasius','knifefish','arapaima'])delete old.state.fishing.fish[key];const g=new F.Farm({save:old,clock:()=>now});
 assert.equal(g.s.coins,f.s.coins);assert.equal(g.s.fishing.fish.carp,2);assert.equal(g.s.fishing.fish.arapaima,0);assert.equal(g.s.fishing.cast.biteAt,c.biteAt);assert.equal(g.s.fishing.cast.poolVersion,undefined);const expected=F.fishingOutcome(c.seed,c.bait,c.rod,c.conditions,1,1),caught=catchFish(g);assert.deepEqual(plain(caught.caught),plain(expected));F.validateSave(JSON.parse(g.serialize()));
 for(const mutation of[s=>s.fishing.fish.arapaima=-1,s=>s.fishing.fish.shark=1,s=>s.fishing.fish.arapaima=10001,s=>s.fishing.cast.poolVersion=4]){const bad=JSON.parse(f.serialize());mutation(bad.state);assert.throws(()=>F.validateSave(bad));}
 for(let seed=0;seed<1000;seed++)assert(['tilapia','carp','catfish','snakehead'].includes(F.fishingOutcome(seed,'worm',3,{night:true,rain:true},5,1).kind));
});
console.log(count+' fishing rules and migration tests passed.');
