const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/farm-engine.js','utf8'),c);const F=c.BaraFarm;let now=1791200000000,count=0;
const plain=v=>JSON.parse(JSON.stringify(v));
function test(name,fn){fn();count++;console.log('✓ '+name);}
function fresh(level=15){const f=new F.Farm({clock:()=>now});f.s.progress.xp=F.LEVEL_XP[level-1];f.s.coins=5000;f.s.materials={wood:200,stone:200,meat:200};return f;}
function pier(){const f=fresh(),p=F.pierPoint(1460);assert(f.build('pier',{x:p.x,y:p.y},0).ok);now+=90000;f.now();assert(f.fishingStarter().ok);return f;}
function cast(f,seed=420){assert(f.startFishing(0,'worm',seed).ok);return f.s.fishing.cast;}
function catchFish(f){const c=f.s.fishing.cast;now=c.biteAt;assert(f.hookFish(c.id).ok);for(let i=1;i<=3;i++){now=c.hookedAt+i*3000;const r=f.reelFish(c.id);assert(r.ok);if(i===3)return r;}}
test('v9 saves retain farm progress and start with empty fishing inventory, without repeating seed gifts',()=>{const f=fresh();f.plant(0,'carrot');const old=plain(JSON.parse(f.serialize()));old.version=9;delete old.state.fishing;const g=new F.Farm({save:old,clock:()=>now});assert.equal(g.s.seeds.carrot,5);assert.equal(g.s.coins,f.s.coins);assert.equal(g.s.plots[0].readyAt,f.s.plots[0].readyAt);assert.equal(g.s.fishing.bait.worm,0);assert(!g.s.fishing.starter);assert.equal(JSON.parse(g.serialize()).version,10);F.validateSave(JSON.parse(g.serialize()));});
test('starter bait is gated by level, claimed once, and persists across reloads',()=>{const f=fresh(2);assert(!f.fishingStarter().ok);f.s.progress.xp=80;assert(f.fishingStarter().ok);assert.equal(f.s.fishing.bait.worm,3);assert(!f.fishingStarter().ok);const g=new F.Farm({save:f.serialize(),clock:()=>now});assert(!g.fishingStarter().ok);assert.equal(g.s.fishing.bait.worm,3);});
test('pier reaches either riverbank, rejects open water and the bridge, and moves without spending again',()=>{for(const rotation of[0,2])for(const y of[100,700,1460,2050]){const f=fresh(),p=F.pierPoint(y,rotation);assert(f.build('pier',{x:p.x,y:p.y},rotation).ok);F.validateSave(JSON.parse(f.serialize()));}const f=pier(),before=f.s.materials.wood;assert(!f.moveBuilding(0,{x:1700,y:1500},0).ok);assert(!f.checkPlacement('pier',{x:F.pierPoint(1115).x,y:1115},0).ok);assert(!f.checkPlacement('pier',{x:640,y:1460},1).ok);const p=F.pierPoint(700,2);assert(f.moveBuilding(0,{x:p.x,y:p.y},2).ok);assert.equal(f.s.materials.wood,before);F.validateSave(JSON.parse(f.serialize()));});
test('casting consumes one bait, uses a completed pier, and early hook or duplicate cast cannot cheat time',()=>{const f=pier(),c=cast(f);assert.equal(f.s.fishing.bait.worm,2);assert(!f.hookFish(c.id).ok);assert(!f.startFishing(0,'worm',333).ok);assert.equal(f.s.fishing.bait.worm,2);assert(!f.moveBuilding(0,{x:F.pierPoint(700).x,y:700},0).ok);assert(!f.sellBuilding(0).ok);assert(!f.startFishing(0,'unknown',333).ok);F.validateSave(JSON.parse(f.serialize()));});
test('server rhythm rejects rapid reels and produces exactly one fish, XP and record after three valid windows',()=>{const f=pier(),c=cast(f);now=c.biteAt;assert(f.hookFish(c.id).ok);assert(!f.reelFish(c.id).ok);const beforeXP=f.s.progress.xp;for(let i=1;i<=3;i++){now=c.hookedAt+i*3000;const r=f.reelFish(c.id);assert(r.ok);if(i<3)assert(!f.reelFish(c.id).ok);else{assert(r.caught);assert.equal(f.s.fishing.fish[r.caught.kind],1);assert.equal(f.s.progress.xp,beforeXP+F.FISH[r.caught.kind].xp);}}assert.equal(f.s.fishing.caught,1);assert.equal(f.used,1);assert.equal(f.s.fishing.records.length,1);assert(!f.reelFish(c.id).ok);F.validateSave(JSON.parse(f.serialize()));});
test('late hook, late reel, cancel and reload never refund consumed bait or grant a catch',()=>{const f=pier(),c=cast(f);now=c.expiresAt+1;assert(f.hookFish(c.id).escaped);assert.equal(f.s.fishing.bait.worm,2);assert.equal(f.used,0);const d=cast(f,87);now=d.biteAt;f.hookFish(d.id);const g=new F.Farm({save:f.serialize(),clock:()=>now});now=d.hookedAt+4601;assert(g.reelFish(d.id).escaped);assert.equal(g.s.fishing.caught,0);assert.equal(g.s.fishing.bait.worm,1);const e=cast(g);assert(g.cancelFishing(e.id).ok);assert.equal(g.s.fishing.bait.worm,0);assert(!g.cancelFishing(e.id).ok);});
test('a fish remains on the line if other work fills the bag, then can be kept once space is free',()=>{const f=pier();f.s.produce.carrot=19;cast(f);f.s.produce.carrot=20;const r=catchFish(f);assert(r.full&&r.landed);assert.equal(f.s.fishing.cast.reels,3);assert.equal(f.s.fishing.caught,0);F.validateSave(JSON.parse(f.serialize()));now+=86400000;f.sell('carrot',1);const kept=f.reelFish(f.s.fishing.cast.id);assert(kept.caught);assert.equal(f.used,20);assert.equal(f.s.fishing.caught,1);assert(!f.startFishing(0,'worm',8).ok);F.validateSave(JSON.parse(f.serialize()));});
test('fish sales use real inventory, count toward bag capacity and protect coin/material limits',()=>{const f=pier();cast(f);const r=catchFish(f),key=r.caught.kind,before=f.s.coins;assert(f.sellFish(key,1).ok);assert.equal(f.s.coins,before+F.FISH[key].sell);assert.equal(f.used,0);assert(!f.sellFish(key,1).ok);assert(!f.sellFish(key,-1).ok);assert(!f.buyBait('worm',101).ok);f.s.fishing.bait.worm=1000;assert(!f.buyBait('worm',1).ok);});
test('rod upgrades have meaningful level/cost gates and cannot change an active cast',()=>{const f=pier();f.s.progress.xp=80;assert(!f.upgradeRod().ok);f.s.progress.xp=260;assert(f.upgradeRod().ok);assert.equal(f.s.fishing.rod,2);cast(f);assert(!f.upgradeRod().ok);f.cancelFishing(f.s.fishing.cast.id);f.s.progress.xp=650;assert(f.upgradeRod().ok);assert(!f.upgradeRod().ok);F.validateSave(JSON.parse(f.serialize()));});
test('save validation rejects forged bait, clocks, fish, pier orientation, records and reel progress',()=>{const f=pier();cast(f);for(const change of[s=>s.fishing.bait.worm=-1,s=>s.fishing.fish.tilapia=1,s=>s.fishing.cast.biteAt--,s=>s.fishing.cast.seed=-1,s=>s.fishing.cast.conditions.night=!s.fishing.cast.conditions.night,s=>s.fishing.cast.reels=3,s=>s.fishing.cast.rod=3,s=>s.buildings[0].rotation=1,s=>s.fishing.records=[{kind:'tilapia',length:900,at:now}]]){const bad=JSON.parse(f.serialize());change(bad.state);assert.throws(()=>F.validateSave(bad));}});
test('fishing rain uses the same world weather and night follows Jakarta, without storing location',()=>{const w={};vm.createContext(w);vm.runInContext(fs.readFileSync('assets/js/farm-weather.js','utf8'),w);for(let i=0;i<100;i++){const at=1791100000000+i*59003;assert.equal(F.fishingConditions(at).rain,w.FarmWeather.at(at).rain>.15);}assert(F.fishingConditions(Date.parse('2026-10-05T13:00:00Z')).night);assert(!F.fishingConditions(Date.parse('2026-10-05T03:00:00Z')).night);for(const bait of Object.keys(F.BAITS))for(let rod=1;rod<=3;rod++){const o=F.fishingOutcome(888,bait,rod,{night:true,rain:true});assert(F.FISH[o.kind]);assert(o.length>=F.FISH[o.kind].min&&o.length<=F.FISH[o.kind].max);}});
console.log(count+' fishing rules and migration tests passed.');
