const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={Math,WORLD_DATA:{bounds:{width:3200,height:2200,originX:1100,originY:740}}};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('assets/js/camera.js','utf8')+'\n'+fs.readFileSync('assets/js/farm-camera.js','utf8')+'\n'+fs.readFileSync('assets/js/farm-pickup.js','utf8')+'\nthis.Camera=FarmCamera;this.Gesture=MapGesture;this.Pickup=FarmPickupGesture;',ctx);
const tests=[],test=(name,fn)=>{fn();tests.push(name);};
function setup(){let time=0,next=0,enabled=true,active=false,lifts=0,drops=0,selects=0,cancels=0,hold=null,point=null,valid=true;const timers=new Map(),camera=new ctx.Camera();camera.resize(1280,720);const base=new ctx.Gesture(camera,()=>selects++);const g=new ctx.Pickup(camera,base,{enabled:()=>enabled,active:()=>active,pick:()=>({id:1}),hold:p=>hold=p,lift:()=>{lifts++;active=true;return true;},move:p=>point=p,drop:()=>{if(valid){drops++;active=false;}},cancel:()=>{cancels++;active=false;g.reset();}},{set:(fn,delay)=>{const id=++next;timers.set(id,{fn,at:time+delay});return id;},clear:id=>timers.delete(id)});
return{g,camera,advance(ms){time+=ms;for(const[id,t]of [...timers])if(t.at<=time){timers.delete(id);t.fn();}},get state(){return{enabled,active,lifts,drops,selects,cancels,hold,point};},setEnabled:v=>enabled=v,setValid:v=>valid=v};}
test('A normal tap remains a single farming click',()=>{const s=setup();s.g.down(1,640,300);s.advance(2999);s.g.up(1,640,300);s.advance(1);assert.equal(s.state.selects,1);assert.equal(s.state.lifts,0);assert.equal(s.state.hold,null);});
test('Holding for three seconds lifts without planting or harvesting',()=>{const s=setup();s.g.down(1,640,300);s.advance(2999);assert.equal(s.state.lifts,0);s.advance(1);assert.equal(s.state.lifts,1);assert.equal(s.state.selects,0);assert.equal(s.state.hold,null);});
test('Dragging a lifted object does not pan and release drops once',()=>{const s=setup(),x=s.camera.x,y=s.camera.y;s.g.down(1,640,300);s.advance(3000);s.g.move(1,740,350);s.g.up(1,740,350);assert.equal(s.camera.x,x);assert.equal(s.camera.y,y);assert.equal(s.state.drops,1);assert.equal(s.state.selects,0);});
test('Releasing the lift in place allows mouse hover then click to drop',()=>{const s=setup();s.g.down(1,640,300);s.advance(3000);s.g.up(1,640,300);assert.equal(s.state.active,true);assert.equal(s.state.drops,0);s.g.move(1,800,400);const target=s.camera.screenToWorld(800,400);assert.equal(s.state.point.x,target.x);s.g.down(1,800,400);s.g.up(1,800,400);assert.equal(s.state.drops,1);assert.equal(s.state.selects,0);});
test('An invalid release keeps the object lifted until a valid location is clicked',()=>{const s=setup();s.setValid(false);s.g.down(1,640,300);s.advance(3000);s.g.move(1,750,400);s.g.up(1,750,400);assert.equal(s.state.active,true);assert.equal(s.state.drops,0);s.setValid(true);s.g.move(1,800,420);s.g.down(1,800,420);s.g.up(1,800,420);assert.equal(s.state.drops,1);});
test('Moving before the hold deadline pans normally and cancels pickup',()=>{const s=setup(),x=s.camera.x;s.g.down(1,640,300);s.g.move(1,660,300);s.advance(4000);s.g.up(1,660,300);assert.notEqual(s.camera.x,x);assert.equal(s.state.lifts,0);assert.equal(s.state.selects,0);});
test('Pinching cancels the hold and never plants on release',()=>{const s=setup();s.g.down(1,500,300);s.g.down(2,600,300);s.advance(4000);s.g.move(2,650,300);s.g.up(2,650,300);s.g.up(1,500,300);assert.equal(s.state.lifts,0);assert.equal(s.state.selects,0);assert.equal(s.state.hold,null);});
test('A second finger cancels a lifted object and returns to pinch navigation',()=>{const s=setup();s.g.down(1,500,300);s.advance(3000);s.g.down(2,600,300);s.g.move(2,650,300);s.g.up(2,650,300);s.g.up(1,500,300);assert.equal(s.state.cancels,1);assert.equal(s.state.drops,0);assert.equal(s.state.selects,0);});
test('Pointer cancellation restores the object without a farming click',()=>{const s=setup();s.g.down(1,640,300);s.advance(3000);s.g.cancel(1);s.g.up(1,640,300);assert.equal(s.state.cancels,1);assert.equal(s.state.drops,0);assert.equal(s.state.selects,0);});
test('Logout or opening a modal before the deadline prevents pickup',()=>{const s=setup();s.g.down(1,640,300);s.setEnabled(false);s.advance(3000);assert.equal(s.state.lifts,0);assert.equal(s.state.hold,null);});
test('Reset clears a pending hold and a later pointer release',()=>{const s=setup();s.g.down(1,640,300);s.g.reset();s.advance(4000);s.g.up(1,640,300);assert.equal(s.state.selects,0);assert.equal(s.state.lifts,0);assert.equal(s.state.hold,null);});
test('Disabled gameplay cannot start gestures',()=>{const s=setup();s.setEnabled(false);s.g.down(1,640,300);s.advance(4000);s.g.up(1,640,300);assert.equal(s.state.selects,0);assert.equal(s.state.lifts,0);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
