const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/farm-engine.js','utf8'),c);const F=c.BaraFarm;let now=1790928000000;const fresh=()=>{const g=new F.Farm({clock:()=>now});g.s.progress.xp=1400;return g;},copy=g=>JSON.parse(g.serialize()),tests=[];function test(name,fn){fn();tests.push(name);}
test('version 4 progress migrates without extra seeds, reset balances or changed crop deadlines',()=>{const g=fresh();g.s.coins=79;g.plant(0,'carrot');g.s.materials={wood:30,stone:20,meat:10};g.build('house',0);const old=copy(g);old.version=4;delete old.state.profile;delete old.state.stats;delete old.state.expansions;old.state.plots.forEach(p=>{delete p.x;delete p.y;});old.state.buildings.forEach(b=>{delete b.x;delete b.y;delete b.rotation;});const next=new F.Farm({save:old,clock:()=>now});assert.equal(next.s.coins,79);assert.equal(next.s.seeds.carrot,5);assert.equal(next.s.plots[0].readyAt,g.s.plots[0].readyAt);assert.equal(next.s.buildings[0].x,F.LOTS[0].x);assert.equal(JSON.parse(next.serialize()).version,7);F.validateSave(copy(next));});
test('arbitrary building placement pays once; moving and rotation preserve deadlines and inventory',()=>{const g=fresh();g.s.materials={wood:30,stone:20,meat:10};assert(g.build('barn',{x:1170,y:740},1).ok);const before=copy(g),b=g.s.buildings[0];assert.equal(b.rotation,1);assert(g.moveBuilding(b.slot,{x:1230,y:815},2).ok);assert.equal(b.readyAt,before.state.buildings[0].readyAt);assert.deepEqual(copy(g).state.materials,before.state.materials);F.validateSave(copy(g));});
test('buildings cannot overlap crops, river, starter cottage, trees or each other',()=>{const g=fresh();g.s.materials={wood:100,stone:100,meat:100};for(const point of [{x:1592,y:1084},{x:650,y:1100},{x:1593,y:872},{x:1788,y:859}]){const before=g.serialize();assert(!g.build('barn',point).ok);assert.equal(g.serialize(),before);}assert(g.build('barn',{x:1170,y:740}).ok);assert(!g.build('well',{x:1170,y:740}).ok);});
test('moving a growing crop keeps its seed count and maturity time, and survives reload',()=>{const g=fresh();g.plant(0,'carrot');const deadline=g.s.plots[0].readyAt;assert(g.movePlot(0,{x:1130,y:1170}).ok);assert.equal(g.s.plots[0].readyAt,deadline);assert.equal(g.s.seeds.carrot,5);const restored=new F.Farm({save:g.serialize(),clock:()=>now});assert.equal(restored.s.plots[0].x,1130);now=deadline;assert(restored.harvest(0).ok);assert.equal(restored.s.stats.harvested,3);});
test('unopened plot defaults are free ground for a growing plot, including after reload and later unlock',()=>{const g=fresh();g.plant(0,'carrot');const destination={x:g.s.plots[9].x,y:g.s.plots[9].y},deadline=g.s.plots[0].readyAt;assert(g.movePlot(0,destination).ok);assert.equal(g.s.plots[0].readyAt,deadline);const saved=copy(g);F.validateSave(saved);const restored=new F.Farm({save:saved,clock:()=>now});restored.s.materials={wood:100,stone:100,meat:100};assert(restored.build('house',{x:1170,y:740}).ok);now+=60000;assert.equal(restored.unlocked,15);assert.equal(restored.s.plots[0].x,destination.x);assert.equal(restored.s.plots[0].y,destination.y);assert.notEqual(restored.s.plots[9].x+':'+restored.s.plots[9].y,destination.x+':'+destination.y);assert.equal(restored.s.plots[0].readyAt,deadline);F.validateSave(copy(restored));});
test('a building can occupy unopened defaults and future plots are placed around it',()=>{const g=fresh();g.s.materials={wood:100,stone:100,meat:100};const destination={x:g.s.plots[20].x,y:g.s.plots[20].y};assert(g.build('barn',destination).ok);F.validateSave(copy(g));g.s.expansions=18;g.ensurePlots();assert.equal(g.unlocked,27);F.validateSave(copy(g));assert.equal(g.s.buildings[0].x,destination.x);assert.equal(g.s.buildings[0].y,destination.y);assert(!g.movePlot(0,destination).ok);assert(!g.movePlot(g.unlocked,{x:1130,y:1170}).ok);});
test('a chosen six-plot garden costs 120 coins and unlocks usable plots at that location',()=>{const g=fresh();g.s.coins=120;assert(g.expandGarden({x:1800,y:1550},6,1).ok);assert.equal(g.s.coins,0);assert.equal(g.unlocked,15);const points=g.gardenPoints({x:1800,y:1550},6,1);for(let i=0;i<6;i++){assert.equal(g.s.plots[i+9].x,points[i].x);assert.equal(g.s.plots[i+9].y,points[i].y);}assert(g.plant(9,'carrot').ok);F.validateSave(copy(g));});
test('failed expansion is atomic and preserves the next-seed budget',()=>{const g=fresh();g.s.coins=125;assert(!g.expandGarden({x:1592,y:1084},6).ok);assert.equal(g.s.coins,125);g.s.seeds.carrot=0;g.s.coins=120;assert(!g.expandGarden({x:1800,y:1550},6).ok);assert.equal(g.unlocked,9);assert.equal(g.s.coins,120);});
test('material kits charge only shortages and never partially spend on failure',()=>{const g=fresh();g.s.materials.wood=3;g.s.coins=40;assert.equal(g.buildKitQuote('barn').cost,26);assert(g.buyBuildKit('barn').ok);assert.equal(g.s.coins,14);assert(g.canBuild('barn'));assert(!g.buyBuildKit('barn').ok);g.s.coins=0;const before=g.serialize();assert(!g.buyBuildKit('house').ok);assert.equal(g.serialize(),before);});
test('profile edits and actual harvest/sale totals are whitelisted and persistent',()=>{const g=fresh();assert(g.updateProfile({name:'  Marcello  ',farmName:'Kebun Apel',avatar:'bee'}).ok);g.plant(0,'carrot');now+=300000;g.harvest(0);g.sell('carrot',3);const next=new F.Farm({save:g.serialize(),clock:()=>now});assert.equal(next.s.profile.name,'Marcello');assert.equal(next.s.profile.avatar,'bee');assert.equal(next.s.stats.harvested,3);assert.equal(next.s.stats.earned,9);assert(!g.updateProfile({name:'',farmName:'Kebun',avatar:'bee'}).ok);assert(!g.updateProfile({name:'x'.repeat(25),farmName:'Kebun',avatar:'bee'}).ok);assert(!g.updateProfile({name:'Pemain',farmName:'Kebun',avatar:'__proto__'}).ok);});
test('server validation rejects overlapping layout, out of bounds, duplicate identities and forged stats',()=>{const g=fresh();for(const mutate of [s=>s.plots[0].x=650,s=>Object.assign(s.plots[0],{x:s.plots[1].x,y:s.plots[1].y}),s=>s.expansions=-1,s=>s.profile.avatar='external-url',s=>s.stats.harvested=true,s=>s.plots[0].id=1]){const data=copy(g);mutate(data.state);assert.throws(()=>F.validateSave(data));}});
const photo=JSON.parse(fs.readFileSync('tests/profile-photo.json','utf8')).photo;
test('uploaded raster avatar round-trips and removal restores emoji without changing the farm',()=>{const g=fresh(),before=copy(g);assert(g.updateProfile({...g.s.profile,photo}).ok);const next=new F.Farm({save:g.serialize(),clock:()=>now});assert.equal(next.s.profile.photo,photo);assert.deepEqual(copy(next).state.materials,before.state.materials);assert.equal(next.s.coins,before.state.coins);assert(next.updateProfile({...next.s.profile,photo:null}).ok);assert(!Object.hasOwn(next.s.profile,'photo'));});
test('profile upload rejects active content, remote URLs and unbounded payloads',()=>{const g=fresh();for(const invalid of ['https://example.com/avatar.jpg','data:image/svg+xml;base64,PHN2Zz4=',photo+'<script>',photo+'A'.repeat(16384),7]){const before=g.serialize();assert(!g.updateProfile({...g.s.profile,photo:invalid}).ok);assert.equal(g.serialize(),before);}const raw=copy(g);raw.state.profile.photo=photo;raw.state.profile.token='discard';assert.equal(F.validateSave(raw).state.profile.token,undefined);});
test('largest garden with a maximum photo remains under the cloud body budget',()=>{const g=fresh();g.s.expansions=72;g.ensurePlots();g.s.profile.photo='data:image/jpeg;base64,/9j/'+ 'A'.repeat(16356);assert.equal(g.s.plots.length,81);assert(Buffer.byteLength(JSON.stringify({save:copy(g),revision:999999999}))<49152);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));

const sample=fresh();sample.s.coins=120;sample.expandGarden({x:1800,y:1550},6,1);sample.s.materials={wood:100,stone:100,meat:100};sample.build('barn',{x:1170,y:740},1);sample.movePlot(0,{x:1130,y:1170});sample.updateProfile({name:'Pekebun Uji',farmName:'Kebun Uji',avatar:'sunflower'});sample.plant(0,'carrot');fs.writeFileSync('tests/farm-studio-save.json',JSON.stringify(F.validateSave(copy(sample)),null,2)+'\n');
