const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Param{constructor(){this.value=0;this.targets=[];}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}cancelScheduledValues(){}setTargetAtTime(v){this.value=v;this.targets.push(v);}}
class Node{constructor(kind){this.kind=kind;this.gain=new Param();this.frequency=new Param();this.pan=new Param();this.Q=new Param();this.threshold=new Param();this.knee=new Param();this.ratio=new Param();this.attack=new Param();this.release=new Param();this.connections=[];this.started=false;this.stopped=false;}connect(n){this.connections.push(n);}disconnect(){this.connections=[];}start(){this.started=true;}stop(time){this.stopped=true;if(time===undefined)this.onended?.();}finish(){this.onended?.();}}
class AudioContext{
 constructor(){this.state='suspended';this.currentTime=0;this.sampleRate=8000;this.destination=new Node('output');this.nodes=[];this.resumes=0;}
 node(kind){const n=new Node(kind);this.nodes.push(n);return n;}createGain(){return this.node('gain');}createDynamicsCompressor(){return this.node('compressor');}createOscillator(){return this.node('tone');}createBufferSource(){return this.node('noise');}createBiquadFilter(){return this.node('filter');}createStereoPanner(){return this.node('pan');}createBuffer(channels,length){return{data:new Float32Array(length),getChannelData(){return this.data;}};}
 async resume(){this.resumes++;this.state='running';this.onstatechange?.();}async suspend(){this.state='suspended';this.onstatechange?.();}
}
const c={window:{},Math};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/farm-audio.js','utf8')+'\nthis.FarmAudio=FarmAudio',c);
const tests=[],test=async(name,fn)=>{await fn();tests.push(name);};
function setup(saved){const store=new Map(saved?[['6xg:audio',JSON.stringify(saved)]]:[]);let creations=0;const ctx=new AudioContext(),audio=new c.FarmAudio({contextFactory:()=>{creations++;return ctx;},storage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},random:()=>.57});return{ctx,audio,store,get creations(){return creations;}};}
const farm={s:{buildings:[]}},camera={x:1590,y:1135,width:1280,worldToScreen(x,y){return{x:640+x-this.x,y:360+(y-this.y)*.5};}};
(async()=>{
 await test('Loading the game never creates or starts an audio context',()=>{const s=setup();s.audio.setActive(true);s.audio.observe(farm,camera,1000);assert.equal(s.creations,0);assert(!s.audio.play('plant'));});
 await test('Missing Web Audio leaves gameplay and settings usable',async()=>{const a=new c.FarmAudio({contextFactory:()=>null,storage:null});assert.equal(await a.unlock(),false);assert.equal(a.unavailable,true);a.configure({volume:.4});assert.equal(a.settings.volume,.4);assert.equal(a.play('plant'),false);});
 await test('One user unlock creates one context and exactly two ambient loops',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();await s.audio.unlock();assert.equal(s.creations,1);assert.equal(s.audio.loops.length,2);assert.equal(s.audio.play('plant'),true);});
 await test('Anonymous visitors hear no farm ambience; an explicit preview remains available',async()=>{const s=setup();await s.audio.unlock();assert.equal(s.audio.loops.length,0);assert(!s.audio.play('plant'));assert(s.audio.play('plant',{preview:true}));});
 await test('Corrupted and out-of-range saved preferences are bounded safely',()=>{const s=setup({enabled:false,volume:12,effects:-2,ambience:'loud'});assert.equal(s.audio.settings.enabled,false);assert.equal(s.audio.settings.volume,1);assert.equal(s.audio.settings.effects,0);assert.equal(s.audio.settings.ambience,.35);s.audio.configure({volume:NaN,ambience:.6});assert.equal(s.audio.settings.volume,1);assert.equal(JSON.parse(s.store.get('6xg:audio')).ambience,.6);});
 await test('Mute immediately stops voices, releases ambient sources and suspends audio',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();s.audio.play('harvest');const loops=[...s.audio.loops];s.audio.configure({enabled:false});assert.equal(s.audio.voices.size,0);assert.equal(s.audio.loops.length,0);assert(loops.every(l=>l.source.stopped));assert.equal(s.ctx.state,'suspended');assert(!s.audio.play('harvest'));assert.equal(JSON.parse(s.store.get('6xg:audio')).enabled,false);});
 await test('Effect and ambience controls remain independent',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();s.audio.configure({effects:0});assert.equal(s.audio.loops.length,2);assert(!s.audio.play('plant'));s.audio.configure({effects:.6,ambience:0});assert.equal(s.audio.loops.length,0);assert(s.audio.play('plant'));assert.equal(s.audio.effects.gain.value,.6);});
 await test('Hidden tabs stop sound and returning resumes without duplicate loops',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();s.audio.play('build');s.audio.construction.set(1,2000);s.audio.setVisible(false);assert.equal(s.audio.loops.length,0);assert.equal(s.audio.voices.size,0);assert.equal(s.audio.construction.size,0);assert.equal(s.ctx.state,'suspended');assert(!s.audio.play('build'));await s.audio.setVisible(true);assert.equal(s.ctx.state,'running');assert.equal(s.audio.loops.length,2);await s.audio.setVisible(true);assert.equal(s.audio.loops.length,2);});
 await test('Logging out silences the farm and drops construction notifications',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();s.audio.construction.set(3,9000);s.audio.setActive(false);assert.equal(s.audio.loops.length,0);assert.equal(s.audio.construction.size,0);assert(!s.audio.play('harvest'));});
 await test('Only construction observed in progress receives one completion cue',async()=>{const s=setup(),heard=[];s.audio.setActive(true);await s.audio.unlock();s.audio.emit=(name)=>heard.push(name);const f={s:{buildings:[{slot:1,x:1590,y:1135,readyAt:2000},{slot:2,x:1700,y:1200,readyAt:500}]}};s.audio.observe(f,camera,1000);assert(!heard.includes('complete'));s.ctx.currentTime=2;s.audio.observe(f,camera,2200);s.ctx.currentTime=4;s.audio.observe(f,camera,2400);assert.equal(heard.filter(n=>n==='complete').length,1);});
 await test('Construction completed while away does not replay a backlog on return',async()=>{const s=setup(),heard=[];s.audio.setActive(true);await s.audio.unlock();s.audio.emit=name=>heard.push(name);const f={s:{buildings:[{slot:1,x:1590,y:1135,readyAt:2000}]}};s.audio.observe(f,camera,1000);s.audio.setVisible(false);await s.audio.setVisible(true);s.audio.observe(f,camera,3000);assert(!heard.includes('complete'));});
 await test('Moving near the river raises water volume and changes its stereo position',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();s.audio.observe(farm,camera,1000);const water=s.audio.loops.find(l=>l.kind==='water'),far=water.gain.gain.value;const near={...camera,x:700};s.audio.observe(farm,near,1100);assert(water.gain.gain.value>far);assert(water.panner.pan.value<0);});
 await test('Rapid repeated actions are throttled; every completed voice disconnects',async()=>{const s=setup();s.audio.setActive(true);await s.audio.unlock();assert(s.audio.play('harvest'));const count=s.audio.voices.size;assert(!s.audio.play('harvest'));assert.equal(s.audio.voices.size,count);const sources=[...s.audio.voices].map(v=>v.source);for(const source of sources)source.finish();assert.equal(s.audio.voices.size,0);assert(sources.every(n=>n.connections.length===0));});
 await test('A burst of overlapping effects cannot exceed the voice budget',async()=>{const s=setup();await s.audio.unlock();for(let i=0;i<30;i++)s.audio.emit('harvest');assert(s.audio.voices.size<=48);s.audio.stopVoices();assert.equal(s.audio.voices.size,0);});
 await test('A browser resume rejection never escapes into game logic',async()=>{const s=setup();s.ctx.resume=async()=>{throw Error('Autoplay denied');};assert.equal(await s.audio.unlock(),false);assert(!s.audio.play('plant'));});
 await test('Server-confirmed success and denied transactions dispatch distinct sounds',async()=>{const played=[],saved=[],results=[{ok:true},{ok:false,message:'Not enough coins'}];const context={gate:{canPlay:true},transactionBusy:false,visiting:null,communityVisitBusy:false,authority:{action:async()=>results.shift()},document:{body:{classList:{add(){},remove(){}}}},audio:{play:name=>played.push(name)},toast:()=>{},save:()=>saved.push(true),renderUI:()=>{}};vm.createContext(context);const source=fs.readFileSync('assets/js/farm-game.js','utf8');vm.runInContext("const harvestT_farm_game_js=value=>typeof BaraI18n!=='undefined'?BaraI18n.t(value):value;",context);vm.runInContext(source.slice(source.indexOf('async function transact('),source.indexOf('function choosePlot(')),context);assert.equal(await context.transact('plant',{id:0,crop:'carrot'},'Planted','plant'),true);assert.equal(await context.transact('seed',{crop:'carrot',qty:1},'Bought','buy'),false);assert.deepEqual(played,['plant','error']);assert.equal(saved.length,1);});
 console.log(JSON.stringify({passed:tests.length,tests},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
