import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import '../assets/js/farm-engine.js';
import {publicView} from '../cloudflare/src/farm-social.mjs';
const F=globalThis.BaraFarm,now=Date.now(),small='https://pbs.twimg.com/profile_images/123/avatar_normal.jpg',photo=small.replace('_normal','');
const f=new F.Farm({clock:()=>now});assert(f.updateProfile({...f.s.profile,accountPhoto:small}).ok);
const row=()=>({user_id:'did:privy:private',revision:5,save:f.serialize(),saved_at:new Date(now).toISOString()});
assert.equal(publicView(row(),now).profile.photo,photo);
const restored=new F.Farm({save:f.serialize(),clock:()=>now});assert.equal(restored.s.profile.accountPhoto,photo);
assert(f.updateProfile({name:'Rizqi',farmName:'Farm X',avatar:'bee',sharePhoto:false}).ok);assert.equal(f.s.profile.accountPhoto,photo);assert.equal(publicView(row(),now).profile.photo,undefined);
assert(f.updateProfile({...f.s.profile,sharePhoto:true,useAccountPhoto:false}).ok);assert.equal(publicView(row(),now).profile.photo,undefined);
const uploaded=JSON.parse(await readFile(new URL('./profile-photo.json',import.meta.url),'utf8')).photo;
delete f.s.profile.sharePhoto;
assert(f.updateProfile({name:'Maya',farmName:'Private photo',avatar:'bee',photo:uploaded}).ok);assert.equal(publicView(row(),now).profile.photo,undefined,'Existing private uploads are not exposed automatically');
assert(f.updateProfile({...f.s.profile,sharePhoto:true}).ok);assert.equal(publicView(row(),now).profile.photo,uploaded);
assert(f.updateProfile({...f.s.profile,accountPhoto:null}).ok);assert.equal(f.s.profile.accountPhoto,undefined);
for(const url of ['javascript:alert(1)','https://evil.example/avatar.jpg','https://pbs.twimg.com@evil.example/a.jpg','https://pbs.twimg.com/profile_images/a.jpg?secret=1'])assert(!f.updateProfile({...f.s.profile,accountPhoto:url}).ok);
const view=publicView(row(),now);for(const secret of ['coins','materials','produce','seeds','log','social','revision','user_id','community'])assert.equal(view[secret],undefined,secret);assert(!JSON.stringify(view).includes('did:privy:private'));
console.log('Shared avatars: persisted X photo, private-upload opt-in, disabled sharing, sanitized URLs, no economic/auth identity exposure passed.');
