const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness({language='en',reduced=false}={}){const nodes={},timers=new Map(),events={},stored={};let id=0,allowed=false,observer;
 function el(name){return nodes[name]||(nodes[name]={hidden:false,inert:false,dataset:{},attrs:{},classes:new Set(),classList:{add(v){nodes[name].classes.add(v)},remove(v){nodes[name].classes.delete(v)},toggle(v,on){on?this.add(v):this.remove(v)}},setAttribute(k,v){this.attrs[k]=v},removeAttribute(k){delete this.attrs[k]},addEventListener(k,fn){events[name+':'+k]=fn},focus(){this.focused=true},close(){this.open=false}});}
 const c={console,Promise,document:{getElementById:el,body:el('body'),querySelector(selector){return selector==='.topbar'?el('topbar'):selector==='#accountBody .account-status'?nodes.authStatus:null;}},BaraI18n:{language},LadangBara:{canPlay:()=>allowed},MutationObserver:class{constructor(fn){observer=fn}observe(){}},matchMedia:()=>({matches:reduced}),setTimeout(fn,ms){timers.set(++id,{fn,ms});return id},clearTimeout(n){timers.delete(n)},location:{reload(){events.reload=true}},localStorage:{setItem(k,v){stored[k]=v}},addEventListener(k,fn){events[k]=fn}};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/game-loading.js','utf8'),c);return{api:c.HarvestLoading,nodes,events,stored,allow(){allowed=true},observe(){observer()},run(ms){for(const[k,v]of [...timers])if(v.ms===ms){timers.delete(k);v.fn()}},timer(ms){return[...timers.values()].some(v=>v.ms===ms)}};}
test('startup hides and locks the map until both validated account and assets have rendered a fresh frame',async()=>{const h=harness();let resolve;h.api.graphics({assetReady:new Promise(r=>resolve=r)});h.api.frameReady();assert.equal(h.nodes.map.inert,true);h.api.identity('did:privy:test');h.allow();h.api.accountReady();h.api.frameReady();assert.notEqual(h.nodes.gameLoading.dataset.state,'ready');resolve();await Promise.resolve();assert.notEqual(h.nodes.gameLoading.dataset.state,'ready');h.api.frameReady();assert.equal(h.nodes.gameLoading.dataset.state,'ready');h.run(550);assert.equal(h.nodes.gameLoading.hidden,true);assert.equal(h.nodes.map.inert,false);assert.equal(h.nodes.body.attrs['aria-busy'],'false');assert(h.nodes.worldCanvas.focused);});
test('even a ready scene cannot open a farm without the existing account gate',()=>{const h=harness();h.api.graphics({});h.api.accountReady();h.api.frameReady();assert(!h.nodes.gameLoading.hidden);assert.equal(h.nodes.map.inert,true);assert.notEqual(h.nodes.gameLoading.dataset.state,'ready');});
test('slow loading offers retry and lighter graphics without pretending loading has completed',()=>{const h=harness();h.run(25000);assert(!h.nodes.bootActions.hidden);assert(h.nodes.map.inert);const hint=h.nodes.bootMessage.textContent;h.api.frameReady();assert.equal(h.nodes.bootMessage.textContent,hint);h.events['bootLight:click']();assert.equal(h.stored['6xg:graphics'],'2d');assert(h.events.reload);});
test('an account failure replaces endless loading with retry; errors during play do not replay the intro',()=>{const h=harness();h.nodes.authStatus={dataset:{state:'error'}};h.observe();assert.equal(h.nodes.gameLoading.dataset.state,'error');assert(!h.nodes.bootActions.hidden);assert(h.nodes.bootLight.hidden);assert(h.nodes.map.inert);h.events['bootRetry:click']();assert(h.events.reload);const playing=harness();playing.allow();playing.api.graphics({});playing.api.accountReady();playing.api.frameReady();playing.run(550);playing.api.fail();assert(playing.nodes.gameLoading.hidden);});
test('reduced motion finishes immediately; a different account waits for a new confirmed frame',()=>{const h=harness({language:'id',reduced:true});h.allow();h.api.graphics({});h.api.accountReady();h.api.frameReady();assert(h.timer(0));h.run(0);assert(h.nodes.gameLoading.hidden);h.api.identity('did:privy:next');assert(!h.nodes.gameLoading.hidden);assert(h.nodes.map.inert);assert.equal(h.nodes.bootTitle.textContent,'Menyiapkan duniamu.');h.api.accountReady();h.api.frameReady();h.run(0);assert(h.nodes.gameLoading.hidden);});
test('critical first-paint cover comes before game styles and loader observes rather than grants account access',()=>{const html=fs.readFileSync('play/index.html','utf8'),source=fs.readFileSync('assets/js/game-loading.js','utf8');assert(html.includes('game-page game-booting'));assert(html.includes('visibility:hidden'));assert(html.indexOf('game-loading.js')<html.indexOf('farm-game.js'));assert(!source.includes('game.attach('));assert(!source.includes('fetch('));assert(!source.includes('aria-valuenow'));const css=fs.readFileSync('assets/css/game-loading.css','utf8');assert(css.includes('prefers-reduced-motion:reduce'));});
