const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.join(__dirname,'..');
function setup({cookie='',stored=null,hostname='6xg.online'}={}){const writes=[],attributes={},context={console,document:{cookie,documentElement:attributes},location:{hostname,reload:()=>writes.push('reload')},localStorage:{getItem:()=>stored,setItem:(k,v)=>writes.push([k,v])}};context.window=context;vm.createContext(context);for(const file of ['i18n-catalog.js','farm-expansion-i18n.js','i18n.js','farm-engine.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets/js',file),'utf8'),context);return{context,writes};}
const en=setup();assert.equal(en.context.BaraI18n.language,'en');assert.equal(en.context.document.documentElement.lang,'en');assert.equal(en.context.BaraI18n.locale,'en-US');assert.equal(en.context.BaraI18n.t('Pilih lokasi di peta'),'Choose a location');assert.equal(en.context.BaraFarm.CROPS.carrot.name,'Carrot');assert.equal(en.context.BaraFarm.RECIPES.jam.name,'Strawberry jam');assert.equal(en.context.BaraFarm.BUILDINGS.barn.name,'Barn');assert.equal(en.context.BaraFarm.CROPS.carrot.minutes,5);assert.equal(en.context.BaraFarm.CROPS.avocado.minutes,1440);
assert.equal(en.context.BaraI18n.defaultName('Kebunku'),'My farm');assert.equal(en.context.BaraI18n.defaultName('Kebun Bima'),'Kebun Bima');assert.equal(en.context.BaraI18n.t('Koin belum cukup. Panen dan jual hasil kebunmu.'),'Not enough coins. Harvest and sell your produce.');
const id=setup({cookie:'other=1; 6xg_language=id',stored:'en'});assert.equal(id.context.BaraI18n.language,'id');assert.equal(id.context.BaraFarm.CROPS.carrot.name,'Wortel');assert.equal(id.context.BaraFarm.RECIPES.jam.name,'Selai stroberi');assert.equal(id.context.BaraI18n.t('Pilih lokasi di peta'),'Pilih lokasi di peta');assert.equal(id.context.BaraI18n.locale,'id-ID');
const invalid=setup({cookie:'6xg_language=invalid',stored:'fr'});assert.equal(invalid.context.BaraI18n.language,'en');invalid.context.BaraI18n.setLanguage('fr');assert.equal(invalid.writes.length,0);invalid.context.BaraI18n.setLanguage('id');assert.match(invalid.context.document.cookie,/6xg_language=id; Path=\/; Max-Age=31536000; SameSite=Lax; Domain=6xg.online; Secure/);assert.equal(invalid.writes.at(-1),'reload');
const app=setup({hostname:'app.6xg.online',cookie:'6xg_language=id'});assert.equal(app.context.BaraI18n.language,'id');
const farm=new en.context.BaraFarm.Farm();assert.equal(farm.s.coins,0);assert.equal(farm.s.seeds.carrot,6);assert.equal(Object.keys(farm.s.production.goods).join(','),'soup,jam,juice,compote,pumpkinSoup,chocolate,pie');assert.equal(farm.s.plots.length,new id.context.BaraFarm.Farm().s.plots.length);
assert.equal(en.context.BaraI18n.t('Dapur kebun'),'Farm kitchen');assert.equal(en.context.BaraI18n.t('DAPUR KEBUN'),'FARM KITCHEN');assert.equal(en.context.BaraI18n.t('6 bibit wortel gratis'),'6 free carrot seeds');assert.equal(en.context.BaraI18n.t('1 JAM'),'1 HOUR');
console.log('Language defaults, shared preference, safe names, English/Indonesian catalogs, and unchanged farm keys passed.');
