const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {source}=require('./load-game.cjs')();
const context={Math,JSON};vm.createContext(context);vm.runInContext(source.split('// Browser interface.')[0]+';globalThis.Camera=MapCamera;globalThis.Gesture=MapGesture;globalThis.World=WORLD;globalThis.Sites=BUILDINGS;globalThis.Camps=CAMPS;',context);
const tests=[];function test(name,fn){fn();tests.push(name);}function close(a,b){assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);}function fresh(w=1000,h=700){const c=new context.Camera();c.resize(w,h);return c;}
test('The expanded world contains all resource sites and three distant camps',()=>{assert(context.World.width*context.World.height>9*1000*720);for(const b of[...Object.values(context.Sites),...context.Camps]){assert(b.x+context.World.originX>0&&b.x+context.World.originX<context.World.width);assert(b.y+context.World.originY>0&&b.y+context.World.originY<context.World.height);}assert(context.Camps.every(c=>Math.hypot(c.x-493,c.y-365)>850));});
test('Screen coordinates round trip through a panned and zoomed camera',()=>{const c=fresh();c.pan(120,-80);c.zoomAt(1.4,430,280);const world=c.screenToWorld(710,451),screen=c.worldToScreen(world.x,world.y);close(screen.x,710);close(screen.y,451);});
test('Zoom keeps the world point under the mouse stationary',()=>{const c=fresh(),before=c.screenToWorld(420,315);c.zoomAt(1.5,420,315);const after=c.screenToWorld(420,315);close(after.x,before.x);close(after.y,before.y);});
test('Dragging and mini-map focus cannot expose empty space outside the world',()=>{const c=fresh();for(const [x,y]of[[1e8,1e8],[-1e8,-1e8],[1e8,-1e8],[-1e8,1e8]]){c.pan(x,y);const b=c.bounds;assert(b.left>=-1e-8&&b.top>=-1e-8);assert(b.left+b.width<=context.World.width+1e-8&&b.top+b.height<=context.World.height+1e-8);}c.focus(0,0);close(c.bounds.left,0);close(c.bounds.top,0);});
test('Minimum zoom fits the viewport and survives mobile to desktop resizing',()=>{const c=fresh(320,600);c.zoomAt(.0001);assert(c.zoom>=c.minZoom);c.resize(1700,900);assert(c.zoom>=c.minZoom);const b=c.bounds;assert(b.width<=context.World.width&&b.height<=context.World.height);c.zoomAt(100);close(c.zoom,2);});
test('A click selects the correct world position after camera movement',()=>{const c=fresh();c.pan(230,-80);let point;const g=new context.Gesture(c,p=>point=p);g.down(1,400,300);g.up(1,401,301);const expected=c.screenToWorld(401,301);close(point.x,expected.x);close(point.y,expected.y);});
test('A mouse drag pans the map without selecting a building',()=>{const c=fresh(),oldX=c.x;let selected=0;const g=new context.Gesture(c,()=>selected++);g.down(1,300,300);g.move(1,420,350);g.up(1,420,350);close(c.x,oldX-120);assert.equal(selected,0);assert.equal(g.pointers.size,0);});
test('Two-finger pinch zooms, then lifting a finger cannot accidentally select',()=>{const c=fresh();let selected=0;const g=new context.Gesture(c,()=>selected++);g.down(1,400,300);g.down(2,500,300);g.move(2,550,300);close(c.zoom,1.5);g.up(2,550,300);g.up(1,400,300);assert.equal(selected,0);assert.equal(g.pointers.size,0);});
test('Cancelled gestures release drag state without selecting',()=>{const c=fresh();let selected=0;const g=new context.Gesture(c,()=>selected++);g.down(5,400,300);g.cancel(5);g.up(5,400,300);g.move(5,500,300);assert.equal(g.pointers.size,0);assert.equal(selected,0);});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
