const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('market is a standalone page with independent account bootstrap and no map or embedded web frame',()=>{const html=fs.readFileSync('market/index.html','utf8');assert(html.includes('href="https://app.6xg.online/market"'));assert(html.includes('market-page.js'));assert(html.includes('farm-market-ui.js'));for(const banned of ['<iframe','worldCanvas','farm-3d','farm-game.js','auth-entry.js'])assert(!html.includes(banned),banned);assert(html.includes('href="/" id="marketBack"'));});
test('every real product photo on the standalone page matches an existing uploaded file',()=>{const source=fs.readFileSync('assets/js/market-page.js','utf8'),keys=source.match(/const marketPhotos=new Set\(\[(.*?)\]\)/s)[1].match(/'([^']+)'/g).map(v=>v.slice(1,-1));for(const key of keys)assert(fs.existsSync('assets/produce/'+key+'.jpg'),key);assert.equal(keys.length,30);});
test('login return selects only the fixed market route, never an arbitrary external destination',()=>{const source=fs.readFileSync('assets/js/online-config.js','utf8');for(const [search,target]of [['?return=market','https://app.6xg.online/market'],['?return=https://evil.example','https://app.6xg.online/'],['','https://app.6xg.online/']]){const c={window:{},location:{search},URLSearchParams};vm.createContext(c);vm.runInContext(source,c);assert.equal(c.window.BARA_ONLINE.playUrl,target);}});
test('game market links navigate to the dedicated route and built game includes that page',()=>{assert.match(fs.readFileSync('assets/js/farm-game.js','utf8'),/if\(view==='market'\)\{window.location.assign\('\/market'\);return;\}/);assert(fs.readFileSync('tools/build-game.mjs','utf8').includes("path.join(output,'market.html')"));});
function pageHarness(fetcher){const nodes={marketContent:{hidden:true},marketGate:{hidden:false}},events={},requests=[];const c={console,URL,URLSearchParams,AbortController,AbortSignal,crypto:globalThis.crypto,performance,Date,queueMicrotask,setTimeout,clearTimeout,setInterval(){},navigator:{onLine:true},location:{origin:'https://app.6xg.online',assign(){}},BARA_ONLINE:{siteOrigin:'https://6xg.online'},BaraI18n:{language:'id',locale:'id-ID',defaultName:v=>v,t:v=>v,localize(){}},BaraFarm:{Farm:class{constructor({save}={}){this.s=save?.state||{profile:{name:'Pekebun',farmName:'Kebunku'},coins:0};}},accountPhotoURL:()=>null},document:{hidden:false,activeElement:null,body:{},getElementById:id=>nodes[id]||(nodes[id]={hidden:false,dataset:{},textContent:'',setAttribute(){},addEventListener:(name,fn)=>events[id+':'+name]=fn}),addEventListener:(name,fn)=>events['document:'+name]=fn},addEventListener:(name,fn)=>events['window:'+name]=fn,fetch:async(url,options)=>{requests.push({url,options});return fetcher(url,options);},resetMarket(){},renderMarket(){},tickMarketUpdates(){},updateMarketForm(){},refreshMarketPurchase(){},marketRenderPending:false};c.window=c;vm.createContext(c);for(const file of ['session-gate.js','cloud-client.js','market-page.js'])vm.runInContext(fs.readFileSync('assets/js/'+file,'utf8'),c);return{c,nodes,requests,events,run:code=>vm.runInContext(code,c)};}
const pageState={userId:'did:privy:market-page-test',revision:2,authoritative:true,serverTime:1791000000000,save:{version:10,state:{coins:300,profile:{name:'Farmer',farmName:'Garden'}}}};
const reply=(data,status=200)=>({status,ok:status>=200&&status<300,json:async()=>data});
test('direct market entry restores the existing cookie-bound account without loading the game',async()=>{const h=pageHarness(async url=>reply(url==='/api/game-session'?{user:{id:pageState.userId}}:pageState));await h.run('startMarketSession()');assert.equal(h.run('gate.canPlay'),true);assert.equal(h.run('farm.s.coins'),300);assert.equal(h.nodes.marketContent.hidden,false);assert.equal(h.nodes.marketGate.hidden,true);assert(h.requests.every(v=>v.options.credentials==='include'));assert(h.requests.every(v=>!v.options.headers?.Authorization));assert.equal(h.run('authority.userId'),pageState.userId);});
test('signed-out direct visits show login; server failure shows retry and never attaches private farm data',async()=>{for(const status of [401,503]){const h=pageHarness(async()=>reply({error:'unavailable'},status));await h.run('startMarketSession()');assert.equal(h.run('gate.canPlay'),false);assert.equal(h.nodes.marketContent.hidden,true);if(status===401)assert.equal(h.nodes.marketLogin.hidden,false);else assert.equal(h.nodes.marketRetry.hidden,false);assert.equal(h.run('authority'),null);}});
test('an identity mismatch in a farm response cannot open the standalone market',async()=>{const h=pageHarness(async url=>reply(url==='/api/game-session'?{user:{id:pageState.userId}}:{...pageState,userId:'did:privy:other'}));await h.run('startMarketSession()');assert.equal(h.run('gate.canPlay'),false);assert.equal(h.nodes.marketRetry.hidden,false);assert.equal(h.run('farm.s.coins'),0);});
test('uncertain transaction confirmation resumes automatically using the retained command route',async()=>{let tries=0;const h=pageHarness(async(url,options)=>{if(options.method==='POST'){tries++;return reply({...pageState,revision:3,result:{ok:true}});}return reply(pageState);});h.run("gate.setIdentity('did:privy:market-page-test');activeSaveKey='6xg-farm:did:privy:market-page-test';gate.attach(activeSaveKey);authority=new BaraFarmSession(location.origin,gate.identity,async()=>null,{cookieSession:true,fetcher:fetch});authority.command={id:crypto.randomUUID(),revision:2,type:'list',args:{}};authority.commandPath='/api/farm-market-action'");await h.run('refreshMarketBalance()');assert.equal(tries,1);assert.equal(h.run('authority.command'),null);assert.equal(h.run('authority.revision'),3);assert.equal(h.requests[0].url,'https://app.6xg.online/api/farm-market-action');});
