import assert from 'node:assert/strict';
import {createSessionBridge,CHANNEL} from '../src/session-bridge.js';
let receive,onload,id=0;const sent=[],states=[],timers=new Map();
const frame={contentWindow:{postMessage:(data,origin)=>sent.push({data,origin})},addEventListener:(name,fn)=>{if(name==='load')onload=fn;},remove(){this.removed=true;}};
const win={location:{origin:'https://app.6xg.online'},crypto:{randomUUID:()=>String(++id)},setTimeout(fn){timers.set(++id,fn);return id;},clearTimeout(id){timers.delete(id);},addEventListener(name,fn){receive=fn;},removeEventListener(){receive=null;}};
const doc={createElement:()=>frame,body:{append:()=>{}}};
const bridge=createSessionBridge({siteOrigin:'https://6xg.online',gameOrigin:'https://app.6xg.online',onState:s=>states.push(s),win,doc});
assert.equal(frame.src,'https://6xg.online/auth/bridge.html');assert.equal(frame.hidden,true);
const send=(origin,source,data)=>receive({origin,source,data});
const authenticated={ready:true,authenticated:true,user:{id:'did:privy:a'}};
send('https://evil.example',frame.contentWindow,{channel:CHANNEL,type:'state',state:authenticated});assert.equal(states.length,0);
send('https://6xg.online',{}, {channel:CHANNEL,type:'state',state:authenticated});assert.equal(states.length,0);
send('https://6xg.online',frame.contentWindow,{channel:'other',type:'state',state:authenticated});assert.equal(states.length,0);
send('https://6xg.online',frame.contentWindow,{channel:CHANNEL,type:'state',state:authenticated});assert.equal(states.length,1);
const token=bridge.request('token');const request=sent.at(-1);assert.equal(request.origin,'https://6xg.online');
send('https://evil.example',frame.contentWindow,{channel:CHANNEL,id:request.data.id,result:'wrong'});
send('https://6xg.online',frame.contentWindow,{channel:CHANNEL,id:'unknown',result:'wrong'});
send('https://6xg.online',frame.contentWindow,{channel:CHANNEL,id:request.data.id,result:'memory-only-token'});assert.equal(await token,'memory-only-token');
assert(!frame.src.includes('token'));assert(!JSON.stringify(authenticated).includes('token'));
const error=bridge.request('token');const failed=sent.at(-1).data;
send('https://6xg.online',frame.contentWindow,{channel:CHANNEL,id:failed.id,error:true});await assert.rejects(error);
const outstanding=bridge.request('logout');bridge.close();await assert.rejects(outstanding);assert(frame.removed);assert.equal(receive,null);assert.equal(timers.size,0);
await assert.rejects(bridge.request('token'));
assert.throws(()=>createSessionBridge({siteOrigin:'https://6xg.online',gameOrigin:'https://app.6xg.online',onState(){},win:{location:{origin:'https://evil.example'}},doc}));
console.log('Session bridge: origin/source isolation, RPC correlation, errors, cleanup, token handling passed.');
