import {after,before,beforeEach,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,exportSPKI,SignJWT} from 'jose';
import {serverFarm,runFarmAction,loadFarm} from '../src/farm-actions.mjs';
const F=globalThis.BaraFarm,keys=await generateKeyPair('ES256'),uid='did:privy:commands',ORIGIN='https://app.6xg.online';let mf,db,jwt;
before(async()=>{
 mf=new Miniflare(convertV4MiniflareOptions({modules:true,scriptPath:new URL('../dist/worker.js',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'),compatibilityDate:'2026-10-01',bindings:{PRIVY_APP_ID:'test-app',PRIVY_VERIFICATION_KEY:await exportSPKI(keys.publicKey),ALLOWED_ORIGINS:ORIGIN+',https://6xg.online'},d1Databases:{DB:'commands-test'},cf:false,telemetry:{enabled:false}}));
 db=await mf.getD1Database('DB');for(const file of['0001_saves.sql','0002_farm_saves.sql','0003_farm_actions.sql'])await db.exec((await readFile(new URL('../migrations/'+file,import.meta.url),'utf8')).replaceAll('\n',' '));
 const now=Math.floor(Date.now()/1000);jwt=await new SignJWT({sub:uid,sid:'signed-test',iss:'privy.io',aud:'test-app',iat:now,exp:now+3600}).setProtectedHeader({alg:'ES256'}).sign(keys.privateKey);
});
beforeEach(async()=>{await db.prepare('DELETE FROM farm_saves').run();await db.prepare('DELETE FROM farm_actions').run();});
after(async()=>mf?.dispose());
const productionFarm=now=>{const f=new F.Farm({clock:()=>now});f.s.progress.xp=150;f.s.buildings.push({slot:0,kind:'kitchen',x:1170,y:740,rotation:0,startedAt:now-120000,readyAt:now});f.s.produce.carrot=12;return f;};
const command=(type,args,revision=0)=>({id:crypto.randomUUID(),revision,type,args});
async function call(method,path,body,auth=jwt,origin=ORIGIN){const r=await mf.dispatchFetch('https://api.example'+path,{method,headers:{...(auth?{Authorization:'Bearer '+auth}:{}),...(origin?{Origin:origin}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json()};}
async function seed(farm){await db.prepare('INSERT INTO farm_saves(user_id,save,revision,saved_at) VALUES (?,?,1,?)').bind(uid,farm.serialize(),new Date().toISOString()).run();}
test('GET supplies a canonical fresh farm but cannot create extra starter rewards',async()=>{const a=await call('GET','/api/farm-save'),b=await call('GET','/api/farm-save');assert.equal(a.status,200);assert.equal(a.data.save.version,9);assert.equal(a.data.save.state.coins,0);assert.equal(a.data.save.state.seeds.carrot,6);assert.equal(a.data.revision,0);assert.equal(b.data.save.state.seeds.carrot,6);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM farm_saves').first()).n,0);});
test('a signed planting sets the exact server deadline and spends one seed',async()=>{const started=Date.now(),r=await call('POST','/api/farm-action',command('plant',{id:0,crop:'carrot'}));assert.equal(r.status,200);assert.equal(r.data.save.state.seeds.carrot,5);const p=r.data.save.state.plots[0];assert(p.plantedAt>=started);assert.equal(p.readyAt-p.plantedAt,300000);assert.equal(r.data.serverTime,p.plantedAt);assert.equal(r.data.revision,1);});
test('forged balances and client crop clocks cannot be uploaded or injected in a command',async()=>{const save=JSON.parse(new F.Farm().serialize());save.state.coins=999999;assert.equal((await call('PUT','/api/farm-save',{save,revision:0})).status,409);for(const payload of[ {...command('plant',{id:0,crop:'carrot'}),coins:99999},command('plant',{id:0,crop:'carrot',readyAt:1}),command('harvest',{id:0,now:9999999999999})])assert.equal((await call('POST','/api/farm-action',payload)).status,400);assert.equal((await call('GET','/api/farm-save')).data.save.state.coins,0);});
test('harvesting before maturity fails against server time even for a signed account',async()=>{assert.equal((await call('POST','/api/farm-action',command('plant',{id:0,crop:'carrot'}))).status,200);const r=await call('POST','/api/farm-action',command('harvest',{id:0},1));assert.equal(r.status,422);assert.equal(r.data.save.state.produce.carrot,0);assert.equal(r.data.revision,1);});
test('repeating one nonce after a lost response never charges or plants twice',async()=>{const p=command('plant',{id:0,crop:'carrot'}),a=await call('POST','/api/farm-action',p),b=await call('POST','/api/farm-action',p);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.data.revision,1);assert.equal(b.data.save.state.seeds.carrot,5);assert(b.data.replayed);assert.equal((await call('POST','/api/farm-action',{...p,args:{id:1,crop:'carrot'}})).status,409);});
test('two devices using one revision cannot overwrite each other',async()=>{const responses=await Promise.all([call('POST','/api/farm-action',command('plant',{id:0,crop:'carrot'})),call('POST','/api/farm-action',command('plant',{id:1,crop:'carrot'}))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const s=(await call('GET','/api/farm-save')).data.save.state;assert.equal(s.seeds.carrot,5);assert.equal(s.plots.filter(p=>p.crop).length,1);});
test('commands require a real account and an allowed browser origin',async()=>{const p=command('plant',{id:0,crop:'carrot'});assert.equal((await call('POST','/api/farm-action',p,null)).status,401);assert.equal((await call('POST','/api/farm-action',p,'a.b.c')).status,401);assert.equal((await call('POST','/api/farm-action',p,jwt,null)).status,403);assert.equal((await call('POST','/api/farm-action',p,jwt,'https://evil.example')).status,403);});
test('server applies a full timed starter journey, XP, orders and barn construction',async()=>{let now=Date.now(),revision=0;async function act(type,args){const r=await runFarmAction(db,uid,command(type,args,revision),now);assert.equal(r.status,200,JSON.stringify(r.data));revision=r.data.revision;return r.data;}
 for(let i=0;i<6;i++)await act('plant',{id:i,crop:'carrot'});now+=300000;for(let i=0;i<6;i++)await act('harvest',{id:i});let s=await loadFarm(db,uid,now);assert.equal(s.save.state.progress.xp,36);assert.equal(F.levelFor(s.save.state.progress.xp),2);
 const id=serverFarm(s.save,now).orders()[0].id;const delivery=command('order',{id},revision);let r=await runFarmAction(db,uid,delivery,now);assert.equal(r.status,200);revision=r.data.revision;assert.equal(r.data.save.state.coins,23);r=await runFarmAction(db,uid,delivery,now);assert.equal(r.data.revision,revision);assert.equal(r.data.save.state.coins,23);
 assert.equal((await runFarmAction(db,uid,command('order',{id},revision),now)).status,422);await act('sell',{crop:'carrot',qty:12});await act('kit',{kind:'barn'});s=await act('build',{kind:'barn',point:{x:1170,y:740},rotation:0});assert.equal(s.save.state.coins,24);assert.equal(serverFarm(s.save,now).tutorialStep(),3);now+=90000;s=await loadFarm(db,uid,now);assert.equal(serverFarm(s.save,now).tutorialStep(),4);assert.equal(serverFarm(s.save,now).capacity,100);assert.equal(s.save.state.seeds.carrot,0);
});
test('locked crop purchases and unfulfilled NPC orders leave balances unchanged',async()=>{const f=new F.Farm();f.s.coins=1000;await seed(f);assert.equal((await call('POST','/api/farm-action',command('seed',{crop:'avocado',qty:1},1))).status,422);const order=f.orders()[0];assert.equal((await call('POST','/api/farm-action',command('order',{id:order.id},1))).status,422);assert.equal((await call('GET','/api/farm-save')).data.save.state.coins,1000);});
test('old farms migrate in place with owned crops, layout and photo preserved',async()=>{const f=new F.Farm();f.s.coins=100;f.s.seeds.apple=2;f.plant(0,'carrot');f.movePlot(0,{x:1130,y:1170});const old=JSON.parse(f.serialize());old.version=5;delete old.state.progress;await db.prepare('INSERT INTO farm_saves(user_id,save,revision,saved_at) VALUES (?,?,1,?)').bind(uid,JSON.stringify(old),new Date().toISOString()).run();const r=await call('GET','/api/farm-save');assert.equal(r.data.save.version,9);assert.equal(r.data.save.state.coins,100);assert.equal(r.data.save.state.seeds.apple,2);assert.equal(r.data.save.state.plots[0].x,1130);assert.equal(r.data.save.state.plots[0].readyAt,old.state.plots[0].readyAt);assert(r.data.save.state.progress.grandfatheredCrops.includes('apple'));const p=command('tutorial',{dismissed:true},1);assert.equal((await call('POST','/api/farm-action',p)).status,200);assert.equal((await call('GET','/api/farm-save')).data.save.state.progress.tutorial.dismissed,true);});
test('profile edits remain bounded and cannot smuggle economic fields',async()=>{assert.equal((await call('POST','/api/farm-action',command('profile',{profile:{name:'Rizqi',farmName:'Kebun Bara',avatar:'bee',coins:50000}}))).status,400);const photo=JSON.parse(await readFile(new URL('../../tests/profile-photo.json',import.meta.url),'utf8')).photo;assert.equal((await call('POST','/api/farm-action',command('profile',{profile:{name:'Rizqi',farmName:'Kebun Bara',avatar:'bee',photo}}))).status,200);const r=await call('GET','/api/farm-save');assert.equal(r.data.save.state.profile.photo,photo);assert.equal(r.data.save.state.coins,0);});
test('production through the authenticated API spends ingredients once and rejects early collection',async()=>{const now=Date.now(),f=productionFarm(now);await seed(f);const p=command('production',{slot:0,recipe:'soup'},1),a=await call('POST','/api/farm-action',p),b=await call('POST','/api/farm-action',p);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.data.save.state.produce.carrot,9);assert.equal(b.data.save.state.production.jobs.length,1);assert.equal(a.data.save.state.production.jobs[0].readyAt-a.data.serverTime,900000);assert.equal((await call('POST','/api/farm-action',command('collect',{id:a.data.result.id},2))).status,422);assert.equal((await call('POST','/api/farm-action',command('production',{slot:0,recipe:'soup',readyAt:1},2))).status,400);});
test('server clock completes queued production while offline; collection and sale commit once',async()=>{let now=Date.now();await seed(productionFarm(now));let r=await runFarmAction(db,uid,command('production',{slot:0,recipe:'soup'},1),now);assert.equal(r.status,200);const id=r.data.result.id;now+=900000;const collect=command('collect',{id},2);r=await runFarmAction(db,uid,collect,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,collect,now);assert.equal(r.data.save.state.production.goods.soup,1);assert.equal(r.data.save.state.challenges.totals.crafted,1);assert.equal(r.data.save.state.progress.xp,154);assert.equal((await runFarmAction(db,uid,command('collect',{id},3),now)).status,422);const sale=command('goods',{recipe:'soup',qty:1},3);r=await runFarmAction(db,uid,sale,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,sale,now);assert.equal(r.data.save.state.coins,16);assert.equal(r.data.save.state.production.goods.soup,0);assert.equal((await runFarmAction(db,uid,command('goods',{recipe:'soup',qty:1},4),now)).status,422);});
test('concurrent reward claims from two devices pay one reward and preserve canonical revision',async()=>{const f=new F.Farm(),now=Date.now();f.s.challenges.counts.planted=3;await seed(f);const id=f.daily()[0].id;const r=await Promise.all([runFarmAction(db,uid,command('daily',{id},1),now),runFarmAction(db,uid,command('daily',{id},1),now)]);assert.deepEqual(r.map(a=>a.status).sort(),[200,409]);const s=(await loadFarm(db,uid,now)).save.state;assert.equal(s.seeds.carrot,8);assert.equal(s.challenges.totals.dailies,1);assert.equal(s.progress.xp,8);assert.equal((await runFarmAction(db,uid,command('daily',{id},2),now)).status,422);});
test('midnight WIB rejects yesterday claims while lifetime achievements remain',async()=>{let now=Date.parse('2026-10-03T16:59:59Z');const f=new F.Farm({clock:()=>now});f.s.challenges.counts.planted=3;f.s.stats.harvested=30;await seed(f);const id=f.daily()[0].id;now+=1000;assert.equal((await runFarmAction(db,uid,command('daily',{id},1),now)).status,422);let r=await runFarmAction(db,uid,command('achievement',{key:'harvester'},1),now);assert.equal(r.status,200);assert.equal(r.data.result.decoration,'planter');assert.equal(r.data.save.state.challenges.counts.planted,0);assert.equal(r.data.save.state.seeds.carrot,9);assert.equal((await runFarmAction(db,uid,command('achievement',{key:'harvester'},2),now)).status,422);});
test('rewards and production are isolated per verified account',async()=>{const now=Date.now(),f=productionFarm(now);f.s.challenges.counts.planted=3;await seed(f);const id=f.daily()[0].id;assert.equal((await runFarmAction(db,'did:privy:another',command('daily',{id}),now)).status,422);assert.equal((await runFarmAction(db,'did:privy:another',command('production',{slot:0,recipe:'soup'}),now)).status,422);assert.equal((await loadFarm(db,uid,now)).save.state.produce.carrot,12);assert.equal((await loadFarm(db,uid,now)).save.state.seeds.carrot,6);});

test('clock clamping preserves valid queue ordering and building completion dependency',()=>{let now=Date.now(),f=productionFarm(now);f.startProduction(0,'soup');f.startProduction(0,'soup');f.s.lastSeen=now+1000;const shifted=serverFarm(JSON.parse(f.serialize()),now);F.validateSave(JSON.parse(shifted.serialize()));assert.equal(shifted.s.production.jobs[1].startedAt,shifted.s.production.jobs[0].readyAt);assert(shifted.s.production.jobs[0].startedAt>=shifted.s.buildings[0].readyAt);});

const animalFarm=(now,kind='coop')=>{const f=new F.Farm({clock:()=>now});f.s.coins=500;f.s.progress.xp=1400;f.s.buildings.push({slot:0,kind,x:1170,y:740,rotation:0,startedAt:now-F.BUILDINGS[kind].seconds*1000,readyAt:now});f.s.produce.corn=4;f.s.produce.carrot=4;return f;};
test('authenticated livestock purchase, feed, offline collection and sale commit exactly once',async()=>{let now=Date.now();await seed(animalFarm(now));let r=await runFarmAction(db,uid,command('animal',{slot:0,kind:'chicken'},1),now);assert.equal(r.status,200);const id=r.data.result.id;const feed=command('feed',{id},2);r=await runFarmAction(db,uid,feed,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,feed,now);assert.equal(r.data.save.state.produce.corn,3);assert.equal(r.data.save.state.livestock.animals[0].readyAt,now+1800000);assert.equal((await runFarmAction(db,uid,command('animal-collect',{id},3),now)).status,422);now+=1800000;const collect=command('animal-collect',{id},3);r=await runFarmAction(db,uid,collect,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,collect,now);assert.equal(r.data.save.state.livestock.produce.egg,3);assert.equal(r.data.save.state.progress.xp,1404);assert.equal((await runFarmAction(db,uid,command('animal-collect',{id},4),now)).status,422);const sale=command('animal-sell',{product:'egg',qty:3},4);r=await runFarmAction(db,uid,sale,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,sale,now);assert.equal(r.data.save.state.coins,456);assert.equal(r.data.save.state.livestock.produce.egg,0);});
test('concurrent livestock collections cannot duplicate inventory and forged feed clocks are rejected',async()=>{const now=Date.now(),f=animalFarm(now);const a=f.buyAnimal(0,'chicken');f.feedAnimal(a.id);await seed(f);const r=await Promise.all([runFarmAction(db,uid,command('animal-collect',{id:a.id},1),now+1800000),runFarmAction(db,uid,command('animal-collect',{id:a.id},1),now+1800000)]);assert.deepEqual(r.map(v=>v.status).sort(),[200,409]);assert.equal((await loadFarm(db,uid,now+1800000)).save.state.livestock.produce.egg,3);assert.equal((await call('POST','/api/farm-action',command('feed',{id:a.id,readyAt:1},2))).status,400);assert.equal((await runFarmAction(db,'did:privy:other',command('feed',{id:a.id}),now)).status,422);});
test('visit routes require signed accounts and never expose private saves or economic identity',async()=>{const now=Date.now(),f=animalFarm(now),code='A123B456C789D012';f.setSharing(true,code);f.s.profile.name='<script>';f.s.profile.farmName='Kebun Teman';f.s.profile.photo=JSON.parse(await readFile(new URL('../../tests/profile-photo.json',import.meta.url),'utf8')).photo;f.buyAnimal(0,'chicken');await seed(f);assert.equal((await call('GET','/api/farm-visit?code='+code,null,null)).status,401);const r=await call('GET','/api/farm-visit?code='+code);assert.equal(r.status,200);assert.equal(r.data.userId,uid);assert.equal(r.data.view.profile.name,'<script>');assert.equal(r.data.view.animals.length,1);for(const key of ['coins','materials','produce','seeds','social','log','production','challenges','progress','stats','photo','user_id','revision'])assert.equal(r.data.view[key],undefined,key);assert.equal(r.data.view.profile.photo,undefined);assert.equal(r.data.save,undefined);assert.equal((await call('POST','/api/farm-visit?code='+code,{})).status,405);assert.equal((await call('GET','/api/farm-visit?code=invalid')).status,400);});
test('sharing is off by default, explicitly enables a random code, and immediately revokes links and friends',async()=>{const now=Date.now(),f=animalFarm(now);await seed(f);const a=await call('POST','/api/farm-action',command('sharing',{enabled:true},1));assert.equal(a.status,200);const code=a.data.save.state.social.code;assert(F.friendCode(code));assert.equal((await call('GET','/api/farm-visit?code='+code)).status,200);assert.equal((await runFarmAction(db,'did:privy:friend',command('friend',{code}),now)).status,200);const lists=await import('../src/farm-social.mjs');let friends=(await lists.socialData(db,'did:privy:friend',null,now)).data.friends;assert.equal(friends[0].available,true);assert.equal(friends[0].profile.farmName,f.s.profile.farmName);assert.equal(friends[0].plots,undefined);const off=await call('POST','/api/farm-action',command('sharing',{enabled:false},2));assert.equal(off.status,200);assert.equal((await call('GET','/api/farm-visit?code='+code)).status,404);friends=(await lists.socialData(db,'did:privy:friend',null,now)).data.friends;assert.equal(friends[0].available,false);assert.equal(friends[0].profile,undefined);});
test('friend commands validate opt-in targets, persist bookmarks and cannot target the owner for writes',async()=>{const now=Date.now(),f=animalFarm(now),code='A123B456C789D012';f.setSharing(true,code);await seed(f);assert.equal((await runFarmAction(db,uid,command('friend',{code},1),now)).status,422);assert.equal((await runFarmAction(db,'did:privy:visitor',command('friend',{code:'FFFFFFFFFFFFFFFF'}),now)).status,422);let r=await runFarmAction(db,'did:privy:visitor',command('friend',{code}),now);assert.equal(r.status,200);assert.deepEqual(r.data.save.state.social.friends,[code]);assert.equal((await runFarmAction(db,'did:privy:visitor',command('friend',{code},1),now)).status,422);assert.equal((await call('POST','/api/farm-action',{...command('animal',{slot:0,kind:'chicken'},1),userId:'did:privy:visitor'})).status,400);assert.equal((await runFarmAction(db,'did:privy:visitor',command('animal',{slot:0,kind:'chicken'},1),now)).status,422);r=await runFarmAction(db,'did:privy:visitor',command('unfriend',{code},1),now);assert.equal(r.status,200);assert.deepEqual(r.data.save.state.social.friends,[]);assert.equal((await loadFarm(db,uid,now)).save.state.coins,500);});
test('v7 migration preserves photos, all inventory and recipe queues while introducing empty private community state',async()=>{const now=Date.now(),f=productionFarm(now);f.startProduction(0,'soup');const raw=JSON.parse(f.serialize());raw.version=7;delete raw.state.social;delete raw.state.livestock;await db.prepare('INSERT INTO farm_saves(user_id,save,revision,saved_at) VALUES (?,?,1,?)').bind(uid,JSON.stringify(raw),new Date().toISOString()).run();const a=await loadFarm(db,uid,now);assert.equal(a.save.version,9);assert.equal(a.save.state.production.jobs[0].readyAt,raw.state.production.jobs[0].readyAt);assert.equal(a.save.state.produce.carrot,9);assert.equal(a.save.state.social.enabled,false);assert.equal(a.save.state.social.code,null);assert.deepEqual(a.save.state.livestock.produce,{egg:0,milk:0});});
test('future legacy clocks clamp livestock deadlines while retaining the exact feed duration',()=>{const now=Date.now(),f=animalFarm(now);const a=f.buyAnimal(0,'chicken');f.feedAnimal(a.id);f.s.lastSeen=now+1000;const restored=serverFarm(JSON.parse(f.serialize()),now);F.validateSave(JSON.parse(restored.serialize()));const animal=restored.s.livestock.animals[0];assert.equal(animal.readyAt-animal.fedAt,1800000);assert(animal.fedAt>=restored.s.buildings[0].readyAt);});
