import {before,beforeEach,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {runFarmAction,loadFarm,parseAction,serverFarm} from '../src/farm-actions.mjs';
import {publicView} from '../src/farm-social.mjs';
const F=globalThis.BaraFarm,uid='did:privy:fishing';let mf,db;
before(async()=>{mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-10-01',d1Databases:{DB:'fishing-test'},cf:false,telemetry:{enabled:false}}));db=await mf.getD1Database('DB');for(const name of['0001_saves.sql','0002_farm_saves.sql','0003_farm_actions.sql'])await db.exec((await readFile(new URL('../migrations/'+name,import.meta.url),'utf8')).replaceAll('\n',' '));});
beforeEach(async()=>{await db.prepare('DELETE FROM farm_saves').run();await db.prepare('DELETE FROM farm_actions').run();});after(async()=>mf?.dispose());
const command=(type,args,revision=0)=>({id:crypto.randomUUID(),type,args,revision});
const fishingFarm=now=>{const f=new F.Farm({clock:()=>now-90000});f.s.progress.xp=1400;f.s.coins=500;f.s.materials={wood:100,stone:100,meat:100};const p=F.pierPoint(1460);assert(f.build('pier',{x:p.x,y:p.y},0).ok);f.clock=()=>now;f.now();return f;};
const seed=async f=>db.prepare('INSERT INTO farm_saves(user_id,save,revision,saved_at) VALUES (?,?,1,?)').bind(uid,f.serialize(),new Date().toISOString()).run();
test('legendary catches persist their full size and replay their sale without duplicating game coins',async()=>{
 let now=Date.now(),revision=1;const f=fishingFarm(now);f.fishingStarter();assert(f.startFishing(0,'worm',83117).ok);const c=f.s.fishing.cast;await seed(f);
 now=c.biteAt;let r=await runFarmAction(db,uid,command('fish-hook',{id:c.id},revision++),now);assert.equal(r.status,200);const hooked=r.data.save.state.fishing.cast.hookedAt;
 for(let i=1;i<=3;i++){now=hooked+i*3000;r=await runFarmAction(db,uid,command('fish-reel',{id:c.id},revision++),now);assert.equal(r.status,200);}
 assert.equal(r.data.result.caught.kind,'arapaima');assert(r.data.result.caught.length>=150);assert.equal(r.data.save.state.fishing.fish.arapaima,1);assert.equal(r.data.save.state.fishing.best,r.data.result.caught.length);
 const restored=await loadFarm(db,uid,now);assert.equal(Object.keys(restored.save.state.fishing.fish).length,9);assert.equal(restored.save.state.fishing.fish.arapaima,1);
 const sale=command('fish-sell',{kind:'arapaima',qty:1},revision++);r=await runFarmAction(db,uid,sale,now);assert.equal(r.status,200);assert.equal(r.data.save.state.coins,2000);assert.equal(r.data.save.state.fishing.fish.arapaima,0);const replay=await runFarmAction(db,uid,sale,now);assert.equal(replay.data.save.state.coins,2000);
});
test('server clock rebasing preserves an active cast and all valid hook/reel deadlines',()=>{let now=Date.now(),f=fishingFarm(now);f.fishingStarter();f.startFishing(0,'worm',1234);const c=f.s.fishing.cast;now=c.biteAt;f.clock=()=>now;f.hookFish(c.id);now=c.hookedAt+3000;f.reelFish(c.id);const old=JSON.parse(f.serialize()),rebased=serverFarm(old,now-40),next=rebased.s.fishing.cast;assert.equal(next.id,c.id);assert.equal(next.reels,1);assert.equal(next.hookedAt,c.hookedAt-40);assert.equal(next.biteAt,c.biteAt-40);assert.equal(rebased.s.fishing.bait.worm,2);F.validateSave(JSON.parse(rebased.serialize()));});
test('starter bait and casting replay one authoritative receipt; client seed and clock injections are rejected',async()=>{const now=Date.now();await seed(fishingFarm(now));const starter=command('fish-starter',{},1);let r=await runFarmAction(db,uid,starter,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,starter,now);assert.equal(r.data.save.state.fishing.bait.worm,3);assert.equal((await runFarmAction(db,uid,command('fish-starter',{},2),now)).status,422);const cast=command('fish-cast',{slot:0,bait:'worm'},2);r=await runFarmAction(db,uid,cast,now);assert.equal(r.status,200);const c=r.data.save.state.fishing.cast;r=await runFarmAction(db,uid,cast,now);assert.equal(r.data.save.state.fishing.bait.worm,2);assert.deepEqual(r.data.save.state.fishing.cast,c);assert.throws(()=>parseAction(command('fish-cast',{slot:0,bait:'worm',seed:1},3)));assert.throws(()=>parseAction(command('fish-hook',{id:c.id,now:c.biteAt},3)));assert.equal((await runFarmAction(db,uid,command('fish-hook',{id:c.id},3),now)).status,422);});
test('timed hook and three server reel windows grant and sell exactly one catch after retries',async()=>{let now=Date.now(),revision=1;const f=fishingFarm(now);f.fishingStarter();await seed(f);let r=await runFarmAction(db,uid,command('fish-cast',{slot:0,bait:'worm'},revision++),now),c=r.data.save.state.fishing.cast;now=c.biteAt;r=await runFarmAction(db,uid,command('fish-hook',{id:c.id},revision++),now);const hooked=r.data.save.state.fishing.cast.hookedAt;assert.equal((await runFarmAction(db,uid,command('fish-reel',{id:c.id},revision),now)).status,422);for(let i=1;i<=3;i++){now=hooked+i*3000;const q=command('fish-reel',{id:c.id},revision++);r=await runFarmAction(db,uid,q,now);assert.equal(r.status,200);const replay=await runFarmAction(db,uid,q,now);assert.equal(replay.data.save.state.fishing.caught,i===3?1:0);}const kind=r.data.result.caught.kind;assert.equal(r.data.save.state.fishing.fish[kind],1);const sale=command('fish-sell',{kind,qty:1},revision++);r=await runFarmAction(db,uid,sale,now);assert.equal(r.status,200);r=await runFarmAction(db,uid,sale,now);assert.equal(r.data.save.state.coins,500+F.FISH[kind].sell);assert.equal(r.data.save.state.fishing.fish[kind],0);assert.equal((await runFarmAction(db,uid,command('fish-sell',{kind,qty:1},revision),now)).status,422);});
test('concurrent last reels cannot duplicate a fish and other accounts cannot use the owner pier',async()=>{let now=Date.now(),f=fishingFarm(now);f.fishingStarter();f.startFishing(0,'worm',1234);const c=f.s.fishing.cast;now=c.biteAt;f.clock=()=>now;f.hookFish(c.id);for(let i=1;i<3;i++){now=c.hookedAt+i*3000;f.reelFish(c.id);}await seed(f);now=c.hookedAt+9000;const responses=await Promise.all([runFarmAction(db,uid,command('fish-reel',{id:c.id},1),now),runFarmAction(db,uid,command('fish-reel',{id:c.id},1),now)]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const state=(await loadFarm(db,uid,now)).save.state;assert.equal(state.fishing.caught,1);assert.equal(Object.values(state.fishing.fish).reduce((a,b)=>a+b,0),1);assert.equal((await runFarmAction(db,'did:privy:other',command('fish-cast',{slot:0,bait:'worm'}),now)).status,422);assert.equal((await runFarmAction(db,'did:privy:other',command('fish-reel',{id:c.id}),now)).status,422);});
test('fishing gear, caught inventory and cast clocks are private when a friend visits',async()=>{const now=Date.now(),f=fishingFarm(now);f.fishingStarter();f.startFishing(0,'worm',4455);f.setSharing(true,'A123B456C789D012');await seed(f);const row=await db.prepare('SELECT save, saved_at FROM farm_saves WHERE user_id=?').bind(uid).first(),view=publicView(row,now);assert.equal(view.buildings[0].kind,'pier');assert.equal(view.fishing,undefined);});
test('pier upgrade receipts charge once, mature exactly, grant tier rewards and include upgrades in the 50% sale',async()=>{let now=Date.now(),revision=1;const f=fishingFarm(now);f.fishingStarter();await seed(f);const upgrade=command('upgrade',{slot:0},revision++);let r=await runFarmAction(db,uid,upgrade,now);assert.equal(r.status,200);assert.equal(r.data.save.state.coins,400);assert.equal(r.data.save.state.materials.wood,52);const finish=r.data.save.state.buildings[0].upgrade.readyAt;assert.equal((await runFarmAction(db,uid,upgrade,now)).data.save.state.coins,400);assert.equal((await runFarmAction(db,uid,command('fish-cast',{slot:0,bait:'worm'},revision),finish-1)).status,422);r=await runFarmAction(db,uid,command('fish-cast',{slot:0,bait:'worm'},revision++),finish);assert.equal(r.status,200);assert.equal(r.data.save.state.buildings[0].level,2);const c=r.data.save.state.fishing.cast;assert.equal((await runFarmAction(db,uid,command('upgrade',{slot:0},revision),finish)).status,422);now=c.biteAt;r=await runFarmAction(db,uid,command('fish-hook',{id:c.id},revision++),now);const hooked=r.data.save.state.fishing.cast.hookedAt;for(let i=1;i<=3;i++){now=hooked+i*3000;r=await runFarmAction(db,uid,command('fish-reel',{id:c.id},revision++),now);assert.equal(r.status,200);}const expected=F.fishingOutcome(c.seed,c.bait,c.rod,c.conditions,2);assert.deepEqual(r.data.result.caught,expected);assert.equal(r.data.result.xp,F.FISH[expected.kind].xp+2);const b=r.data.save.state.buildings[0];r=await runFarmAction(db,uid,command('building-sell',{slot:0,kind:'pier',startedAt:b.startedAt},revision++),now);assert.equal(r.status,200);assert.equal(r.data.save.state.coins,450);assert.equal(r.data.save.state.materials.wood,76);assert.equal(r.data.save.state.materials.stone,92);assert.equal(r.data.save.state.buildings.length,0);assert.throws(()=>parseAction(command('upgrade',{slot:0,level:5},revision)));assert.equal((await runFarmAction(db,'did:privy:other',command('upgrade',{slot:0}),now)).status,422);});
