import {after,before,beforeEach,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {exportSPKI,generateKeyPair,SignJWT} from 'jose';
import {digest,authorizeNative,exchangeNative,nativeIdentity} from '../src/native-auth.mjs';
const keys=await generateKeyPair('ES256');let mf,db;
before(async()=>{mf=new Miniflare(convertV4MiniflareOptions({modules:true,scriptPath:new URL('../dist/worker.js',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'),compatibilityDate:'2026-10-01',bindings:{PRIVY_APP_ID:'native-test',PRIVY_VERIFICATION_KEY:await exportSPKI(keys.publicKey),ALLOWED_ORIGINS:'https://6xg.online,https://app.6xg.online'},d1Databases:{DB:'native-tests'},cf:false,telemetry:{enabled:false}}));db=await mf.getD1Database('DB');for(const name of ['0001_saves.sql','0002_farm_saves.sql','0003_farm_actions.sql','0004_native_sessions.sql'])await db.exec((await readFile(new URL('../migrations/'+name,import.meta.url),'utf8')).replaceAll('\n',' '));});
beforeEach(async()=>{for(const name of ['native_auth_codes','native_sessions','farm_saves','farm_actions'])await db.prepare('DELETE FROM '+name).run();});after(async()=>mf?.dispose());
const verifier='v'.repeat(43),uid='did:privy:native';
async function grant(){return authorizeNative(db,uid,{challenge:await digest(verifier)});}
async function call(path,{auth,body,origin='https://app.6xg.online',method='POST'}={}){const response=await mf.dispatchFetch('https://test.example'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return{status:response.status,data:await response.json()};}
test('PKCE rejects a wrong verifier without consuming the code, then exchanges once',async()=>{const {data}=await grant();assert.equal((await exchangeNative(db,{code:data.code,verifier:'x'.repeat(43)})).status,401);const session=await exchangeNative(db,{code:data.code,verifier});assert.equal(session.status,200);assert.equal(await nativeIdentity(db,session.data.token),uid);assert.equal((await exchangeNative(db,{code:data.code,verifier})).status,401);const stored=await db.prepare('SELECT * FROM native_sessions').first();assert.notEqual(stored.token_hash,session.data.token);assert.equal(stored.expires_at-stored.created_at,30*86400000);});
test('concurrent exchanges mint one session and expired grants do not authorize',async()=>{const {data}=await grant();const results=await Promise.all([exchangeNative(db,{code:data.code,verifier}),exchangeNative(db,{code:data.code,verifier})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,401]);const old=await authorizeNative(db,uid,{challenge:await digest(verifier)},100);assert.equal((await exchangeNative(db,{code:old.data.code,verifier},120101)).status,401);});
test('fixed strict bodies reject injected users, callback URLs and malformed proof',async()=>{assert.equal((await authorizeNative(db,uid,{challenge:await digest(verifier),userId:'did:privy:other'})).status,400);assert.equal((await authorizeNative(db,uid,{challenge:await digest(verifier),redirect:'https://evil.example'})).status,400);assert.equal((await exchangeNative(db,{code:'abc',verifier})).status,400);});
test('account photo handoff only accepts sanitized X photos and never takes an identity from profile data',async()=>{const challenge=await digest(verifier);for(const photo of ['http://pbs.twimg.com/profile_images/1/a.jpg','https://evil.example/profile_images/a.jpg','https://pbs.twimg.com/profile_images/a.jpg?secret=yes','data:image/jpeg;base64,x'])assert.equal((await authorizeNative(db,uid,{challenge,accountPhoto:photo})).status,400);const g=await authorizeNative(db,uid,{challenge,accountPhoto:'https://pbs.twimg.com/profile_images/123/avatar_normal.jpg'});const s=await exchangeNative(db,{code:g.data.code,verifier});assert.equal(s.data.accountPhoto,'https://pbs.twimg.com/profile_images/123/avatar.jpg');assert.equal(s.data.userId,uid);});
test('browser Privy identity opens a native session that reads the same farm and revokes on logout',async()=>{const jwt=await new SignJWT({sub:uid,sid:'session',iss:'privy.io',aud:'native-test'}).setProtectedHeader({alg:'ES256'}).setIssuedAt().setExpirationTime('1h').sign(keys.privateKey);const grant=await call('/api/native-authorize',{auth:jwt,body:{challenge:await digest(verifier)},origin:'https://6xg.online'});assert.equal(grant.status,200);const session=await call('/api/native-exchange',{body:{code:grant.data.code,verifier}});assert.equal(session.status,200);const read=await call('/api/farm-save',{auth:session.data.token,method:'GET'});assert.equal(read.status,200);assert.equal(read.data.userId,uid);assert.equal(read.data.save.state.seeds.carrot,6);assert.equal((await call('/api/native-authorize',{auth:session.data.token,body:{challenge:await digest(verifier)}})).status,401);assert.equal((await call('/api/native-logout',{auth:session.data.token,body:{}})).status,200);assert.equal((await call('/api/farm-save',{auth:session.data.token,method:'GET'})).status,401);});
test('wrong origins, missing login, expiry and altered tokens cannot access a farm',async()=>{assert.equal((await call('/api/native-authorize',{body:{challenge:await digest(verifier)}})).status,401);assert.equal((await call('/api/native-exchange',{body:{},origin:'https://evil.example'})).status,403);const g=await grant(),s=await exchangeNative(db,{code:g.data.code,verifier});assert.equal((await call('/api/farm-save',{auth:s.data.token+'x',method:'GET'})).status,401);await db.prepare('UPDATE native_sessions SET expires_at=0').run();assert.equal((await call('/api/farm-save',{auth:s.data.token,method:'GET'})).status,401);});
