"""Build the playable world's static scenery before it reaches the browser."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "data" / "world.json"
OUTPUT = ROOT / "assets" / "js" / "world-data.js"
SITE_KEYS = {"barracks", "tower", "wall", "townhall", "lumber", "quarry", "mine", "hunt"}


def validate(config: dict) -> None:
    if config.get("version") != 1:
        raise ValueError("Unsupported world version")
    bounds = config["bounds"]
    for key in ("width", "height", "originX", "originY"):
        value = bounds[key]
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value <= 0:
            raise ValueError(f"Invalid world bound: {key}")
    if bounds["width"] > 6000 or bounds["height"] > 4000:
        raise ValueError("World exceeds the renderer's scenery budget")
    if set(config["sites"]) != SITE_KEYS or len(config["camps"]) != 3:
        raise ValueError("World must contain eight village sites and three camps")
    for point in [*config["sites"].values(), *config["camps"]]:
        for key in ("x", "y"):
            if isinstance(point[key], bool) or not isinstance(point[key], (int, float)) or not math.isfinite(point[key]):
                raise ValueError("Site coordinates must be finite numbers")
        if not 0 < point["x"] + bounds["originX"] < bounds["width"] or not 0 < point["y"] + bounds["originY"] < bounds["height"]:
            raise ValueError("A site lies outside the world")
    for count in config["vegetation"].values():
        if isinstance(count, bool) or not isinstance(count, int) or not 0 <= count <= 5000:
            raise ValueError("Invalid scenery count")
    if isinstance(config["seed"], bool) or not isinstance(config["seed"], int):
        raise ValueError("The world seed must be an integer")


def build(config: dict) -> str:
    validate(config)
    bounds = config["bounds"]
    seed = config["seed"]

    def rand() -> float:
        nonlocal seed
        seed = (seed * 1664525 + 1013904223) % (2 ** 32)
        return seed / (2 ** 32)

    points = [*config["sites"].values(), *config["camps"]]
    trees, grass, rocks = [], [], []
    for _ in range(config["vegetation"]["treeCandidates"]):
        x, y = rand() * bounds["width"] - bounds["originX"], rand() * bounds["height"] - bounds["originY"]
        distant = all(math.hypot(x - p["x"], y - p["y"]) > (95 if i < 8 else 110) for i, p in enumerate(points))
        valley = math.hypot((x - 493) / 1.45, y - 365)
        if distant and (valley > 320 or x < 160 or y < 65 or (x < 350 and y > 370)):
            size, shade = 19 + rand() * 20, rand()
            pine = y < 10 or rand() > .55
            trees.append([round(x, 1), round(y, 1), round(size, 1), round(shade, 3), int(pine)])
    trees.sort(key=lambda t: t[1])
    for _ in range(config["vegetation"]["grassCount"]):
        grass.append([round(rand() * bounds["width"] - bounds["originX"], 1), round(rand() * bounds["height"] - bounds["originY"], 1), round(2 + rand() * 4, 1), round(.1 + rand() * .18, 3)])
    for i in range(config["vegetation"]["rockCount"]):
        remote = i > 36
        rocks.append([round((1060 if remote else 725) + (rand() - .5) * (440 if remote else 150), 1), round((-360 if remote else 435) + (rand() - .5) * (190 if remote else 110), 1), round(8 + rand() * 16, 1), int(remote and rand() > .4)])
    data = {"bounds": bounds, "sites": config["sites"], "camps": config["camps"], "trees": trees, "grass": grass, "rocks": rocks}
    return "// Generated by tools/build_world.py; edit data/world.json instead.\n'use strict';\nconst WORLD_DATA=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if published scenery differs from its source")
    args = parser.parse_args()
    output = build(json.loads(CONFIG.read_text(encoding="utf-8")))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != output:
            raise SystemExit("World data is outdated. Run python tools/build_world.py")
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        if refresh_asset_versions(html) != html:
            raise SystemExit("Asset versions are outdated. Run python tools/build_world.py")
        print("World data matches its source")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output, encoding="utf-8")
        index = ROOT / "index.html"
        if index.exists():
            index.write_text(refresh_asset_versions(index.read_text(encoding="utf-8")), encoding="utf-8")
        print(f"Built world scenery: {len(output):,} characters")


def refresh_asset_versions(html: str) -> str:
    """Version every shipped asset so a new release cannot reuse stale scripts."""
    def version(match: re.Match) -> str:
        relative = match.group(1)
        file = (ROOT / relative[2:]).resolve()
        if ROOT not in file.parents or not file.is_file():
            raise ValueError(f"Missing game asset: {relative}")
        fingerprint = hashlib.sha256(file.read_bytes()).hexdigest()[:10]
        return relative + "?v=" + fingerprint
    return re.sub(r'(\./assets/[^"?]+)\?v=[^"\s]+', version, html)


if __name__ == "__main__":
    main()
